add power attack feat slider / standardize UI
ChrisPJohn/SolastaCommunityExpansion pull request #109
Opened 2021-11-19 05:28 UTC by ThyWoof

2021-11-19 05:58 UTC, ChrisPJohn requested changes
The reason I didn't just add a slider before is the actual text of the feat is hard coded to -3/+6 and that text should be updated with the changing values.

2021-11-19 14:25 UTC, ThyWoof commented
@ChrisPJohn , changed all descriptions to be dynamic. Set restart_required. It might be possible on an upcoming release to remove this restart dependency.

2021-11-20 01:39 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Viewers/Displays/FeatsDisplay.cs
> +            if (UI.Slider("Power Attack modifier ".white() + reqRestart, ref intValue, 1, 6, 3, ""))
Does it actually require restart though?

2021-11-20 01:39 UTC, ChrisPJohn approved these changes

2021-11-20 14:42 UTC, ThyWoof commented
it was closed by mistake.

2021-11-20 14:43 UTC, merged