character export with changes from other request
ChrisPJohn/SolastaCommunityExpansion pull request #138
Opened 2021-11-22 20:18 UTC by ThyWoof

. removed loggers
. added a message to inform hero with same name
. fixed a bug with classes without surnames

2021-11-22 20:19 UTC, ThyWoof commented
taking from other request...

2021-11-22 21:43 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/CharacterExportContext.cs
> +                if (newFirstName.Contains(" "))
Should we also check if(string.IsNullOrWhitespace(...)) { Alert }?

2021-11-22 21:45 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/CharacterExportContext.cs
> +                if (newFirstName.Contains(" "))
Should it be` if(racePresentation.HasSurName && newFirstName.Contains(" "))`

2021-11-22 21:47 UTC, PhilPJL requested changes
See comments

2021-11-22 22:31 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/CharacterExportContext.cs
> +                if (newFirstName.Contains(" "))
good catch. will add this check.

2021-11-22 22:42 UTC, PhilPJL submitted a review, later dismissed

2021-11-23 05:32 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Models/CharacterExportContext.cs
> +                heroCharacter.SetGuid(0);
I wonder if we should be calling heroCharacter.Unregister() and heroCharacter.ResetForOutgame() here?

This is based on HeroStatsColumn::OnUpdateCharacterCb

  public void OnUpdateCharacterCb()
  {
    this.UpdatedToDisk = true;
    this.updateFileButton.interactable = false;
    ICharacterPoolService service = ServiceRepository.GetService<ICharacterPoolService>();
    this.GuiCharacter.RulesetCharacterHero.Unregister();
    this.GuiCharacter.RulesetCharacterHero.ResetForOutgame();
    RulesetCharacterHero rulesetCharacterHero = this.GuiCharacter.RulesetCharacterHero;
    service.SaveCharacter(rulesetCharacterHero);
  }

2021-11-23 05:32 UTC, ChrisPJohn requested changes
See comment about maybe calling unregister and resetforoutgame

2021-11-23 05:56 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/CharacterExportContext.cs
> +                heroCharacter.SetGuid(0);
I only wrote the pop up code. @PhilPJL ?

2021-11-23 13:32 UTC, PhilPJL requested changes

2021-11-23 13:32 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/CharacterExportContext.cs
> +                heroCharacter.SetCurrentHitPoints(heroCharacter.CurrentHitPoints + heroCharacter.MissingHitPoints);
This changes the in-game hp.  Need to save current hp and restore later on.

2021-11-23 13:33 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/CharacterExportContext.cs
> +                heroCharacter.SetGuid(0);
I did try those methods when they appeared thinking they would simplify things, but they don't because they're intended to work out of game.

2021-11-23 17:07 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/CharacterExportContext.cs
> +                heroCharacter.Unregister();
cleaned up more code and now using Unregister() / Register() pair. Powers, Spells and Conditions still need to be saved manually.

2021-11-23 17:08 UTC, ThyWoof commented
@PhilPJL , trying to reuse as much as possible original TA code. It looks like we don't need to keep a tab on inventory items if we use Unregister / Register. Tested on a few saves.

2021-11-23 17:09 UTC, ThyWoof commented
Will remove commented code after we agree on a final version.

2021-11-23 17:40 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/CharacterExportContext.cs
> +                    if (rulesetEntity is RulesetItem)
Remove these empty statements

2021-11-23 17:42 UTC, PhilPJL approved these changes
Looks good seems to work fine.  My only issue is that the text input needs a border or different colour background and needs to get the focus when the modal is opened.

2021-11-23 19:36 UTC, ThyWoof commented
made more changes but sometimes git gets on my way... closing this and will open a new one with latest dev commit.

2021-11-23 19:36 UTC, closed without merging