Combat surprise
ChrisPJohn/SolastaCommunityExpansion pull request #189
Opened 2021-12-07 06:19 UTC by ThyWoof

. Implements surprise rules much closer to SRD:

for each surprised entity:
  for each surprising entity in field of vision:
    roll surprising entity stealth check against passive surprised entity perception check
if at least one roll fails surprised entity isn't surprised anymore

2021-12-07 06:20 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/144976930-716db0ec-918d-42e5-83f4-7dd537e151a2.png)
here both heroes succeed on the stealth check so enemy got surprised.

2021-12-07 06:22 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/144977125-e1aa4e65-b1de-426d-b142-81bbd1ad1ffc.png)
here was playing with 4 heroes and second one failed. remaining heroes didn't roll stealth and enemy wasn't surprised anymore

2021-12-07 06:23 UTC, ThyWoof commented
Note that different than TT rules it will roll a new stealth check for each (surprised, surprising) tuples. It's a computer...

2021-12-07 08:48 UTC, ChrisPJohn requested changes
Please switch to using an early exit instead of an if around nearly the entire method.

Also I added some thoughts on how to make it closer to tabeltop rules.

2021-12-07 08:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/SrdAndHouseRulesContext/GameLocationBattlePatcher.cs
> +            if (surprised)
You should start the method with an early exit instead of this if:

if(!surprised) {
return;
}

That reduces the indentation of everything.

2021-12-07 08:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/SrdAndHouseRulesContext/GameLocationBattlePatcher.cs
> +                            surprisingCharacter.RollAbilityCheck("Dexterity", "Stealth", perceptionOnTarget, RuleDefinitions.AdvantageType.None, new ActionModifier(), false, -1, out RuleDefinitions.R
I saw there were comments in the discord about using an opposed check instead of the passive perception. Do we want to make that change?

My thought is we can iterate over the surprising characters and roll stealth checks, then iterate over the surprised characters and roll perception checks. If the surprised character rolls below all of the stealth checks of characters they can see, they're surprised, otherwise that character is not surprised.

This would mean we don't do nested foreach and I think gets it closer to the table top rules. The only issue is needing to specify a dc for the skill check.

The other possibility is to use ResolveContestCheck, though then we're back to a contested check for each pair.

2021-12-07 15:13 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/SrdAndHouseRulesContext/GameLocationBattlePatcher.cs
> +            if (surprised)
not here. It's an if-else...

2021-12-07 15:15 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/SrdAndHouseRulesContext/GameLocationBattlePatcher.cs
> +                            surprisingCharacter.RollAbilityCheck("Dexterity", "Stealth", perceptionOnTarget, RuleDefinitions.AdvantageType.None, new ActionModifier(), false, -1, out RuleDefinitions.R
I would rather have it as is and get further feedback from players...

2021-12-07 16:32 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/SrdAndHouseRulesContext/GameLocationBattlePatcher.cs
> +            if (surprised)
Still refactored code a bit to only have one outer loop

2021-12-07 19:53 UTC, ThyWoof commented
added a new dummy unsurprised condition so it clear reflects on console. FYI @ChrisPJohn

2021-12-07 20:19 UTC, PhilPJL submitted a review, later dismissed

2021-12-08 00:30 UTC, ThyWoof commented
we had a chance to test this and fix a bug on passive perception calc on monsters...

2021-12-08 01:32 UTC, ChrisPJohn requested changes
See comments

2021-12-08 01:32 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Models/SrdAndHouseRulesContext.cs
> +            var conditionAware = UnityEngine.Object.Instantiate(dbConditionDefinition.GetElement("ConditionSurprised"));
Is there a reason not to use a conditiondefinition builder here?

2021-12-08 01:32 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/SrdAndHouseRules/GameLocationBattlePatcher.cs
> +                Models.SrdAndHouseRulesContext.StartContenders(partySurprised, __instance.PlayerContenders, __instance.EnemyContenders);
Is it possible for both groups to be surprised or do we really only need to call one of these 2 each time?

2021-12-08 02:08 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/SrdAndHouseRules/GameLocationBattlePatcher.cs
> +                Models.SrdAndHouseRulesContext.StartContenders(partySurprised, __instance.PlayerContenders, __instance.EnemyContenders);
both cannot be surprised. still need to call both as all contenders must be initialized. when our StartContender gets called with surprised = false it will default to standard game output (the inner for loop never executes and contender is started as not surprised).

2021-12-08 02:21 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/SrdAndHouseRulesContext.cs
> +                if (surprised)
no. trust me. this if as is is required... otherwise a contender won't be added to battle.

2021-12-08 03:55 UTC, ThyWoof commented
closing this as refactored Game Console touching less files

2021-12-08 03:55 UTC, closed without merging