Item options
ChrisPJohn/SolastaCommunityExpansion pull request #200
Opened 2021-12-10 22:25 UTC by ThyWoof

2021-12-10 22:28 UTC, ThyWoof commented
@Silvergriffon : here is Item Options almost fully migrated. We are still missing the custom Empress Garb textures... Please review these changes to ensure I didn't break anything. I'll add Empress Garb changes later on.

2021-12-10 22:54 UTC, PhilPJL commented on SolastaCommunityExpansion/Viewers/Displays/ItemsAndCraftingDisplay.cs
> +                var keys = ItemCraftingContext.RecipeBooks.Keys;
You could do this

```
	foreach (var keygroup in keys.Buffer((int)(keys.Count() + 1) / 2))
	{
		using (UI.HorizontalScope())
		{
			foreach (var key in keygroup)
			{
				AddUIForWeaponKey(key);
			}
		}
	}
```

But that would rely on adding System.Interactive Nuget package.

2021-12-10 22:57 UTC, PhilPJL approved these changes

2021-12-10 23:00 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/ItemOptionsContext.cs
> +            foreach (ItemDefinition item in DatabaseRepository.GetDatabase<ItemDefinition>().Where(x => x.ArmorDescription.ArmorType == "ClothesType" && !x.Magical && !x.Name.Contains("_Tattoo") && !
Probably a personal style thing but I usually split .Where && clauses like

```
DatabaseRepository.GetDatabase<ItemDefinition>()
	.Where(x => x.ArmorDescription.ArmorType == "ClothesType")
	.Where(x => !x.Magical)
	.Where(x => !x.Name.Contains("_Tattoo"))
	.Where(x => !x.SlotsWhereActive.Contains("TabardSlot")
```

I think that's more readable - although technically slower.

2021-12-11 00:15 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/ItemOptionsContext.cs
> +            foreach (ItemDefinition item in DatabaseRepository.GetDatabase<ItemDefinition>().Where(x => x.ArmorDescription.ArmorType == "ClothesType" && !x.Magical && !x.Name.Contains("_Tattoo") && !
agreed it's slower. made 2 lines for readability.

2021-12-11 01:38 UTC, ThyWoof commented
migration complete. Empress Garb is in. FYI @Silvergriffon .

2021-12-11 09:57 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/ItemOptionsContext.cs
> +                var maleBodyPartBehaviours = AccessTools.Field(itemPresentation.GetType(), "maleBodyPartBehaviours").GetValue(itemPresentation) as GraphicsCharacterDefinitions.BodyPartBehaviour[];
You can use:
`var maleBodyPartBehaviours = itemPresentation.GetBodyPartBehaviours(CreatureSex.Male)`

2021-12-11 09:58 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/ItemOptionsContext.cs
> +                if (!stock.ItemDefinition.Name.Contains("Manual"))
Combine these ifs?

2021-12-11 10:00 UTC, PhilPJL commented on SolastaCommunityExpansion/Viewers/Displays/CharacterDisplay.cs
> +        private static bool DisplayFaceUnlockSettings { get; set; } = false;
Initializing a property to it's default value will generate a warning.

2021-12-11 10:03 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/ItemOptionsContext.cs
> +        private static ItemPresentation EmpressGarbOriginalItemPresentation { get; set; } = null;
Initializing a property to it's default value will generate a warning.

2021-12-11 10:04 UTC, PhilPJL requested changes
Small changes noted

2021-12-11 13:05 UTC, PhilPJL submitted a review, later dismissed

2021-12-11 13:15 UTC, PhilPJL approved these changes

2021-12-11 13:15 UTC, merged