Witch class - DO NOT MERGE
ChrisPJohn/SolastaCommunityExpansion pull request #206
Opened 2021-12-11 19:38 UTC by RealBazou

DO NOT MERGE

This is mostly for feedback. 

I have a lot of questions still and am mostly looking for guidance and to start a dialog with the veterans.

Here are notes I have taken, as well as more notes in the comments in the code:

- subclasses are totally empty, it is not ready yet
- equipment rows, not sure how to clean it up with drop downs
- Eldritch Orb: main hit should do 1d8, aoe should do half, right now not sure how to separate this?
- Minor lifesteal: should give back the damage as temporary hit points, not sure hw to do taht. Tried Vampiric Touch, not sure.
- Find Familiar: Can summon an infinite amount of familiars, this should not be
- Find Familiar: Limited to Help action, nothing else like cast from a distance, or whatnot
- Frenzy: unable to test lvl 6+ spells, I can't seem to have 6+ spell slots, not sure why?
- Unable to give Witch Curse at level 1 (paritularly bonus cantrip from Burned), I suspect it's because spell slots don't exist yet at that point during character creation?
- Visions Witch Curse: how to give a charisma based bonus on initiative? flat bonus is easy, but cha based... ?
- Maledictions: I have no idea how to implement a 2nd concentration mechanic... that is above my pay grade...
- Maledictions at level 1 are apart during character creation, and 2nd one is off screen, i.e.e requires scrolling, can be missed
- Familiar Power is nowhere near what it is supposed to be, i.e. an improved familiar form. More work needs to be done here.
- Cackle: not implemented, but would be great. It refreshes existing Maledictions and bypasses the need to do another saving throw.
- Insidious Spell: how to apply a debuff on a creature which has a Malediction? How to make that debuff only apply to your spells?
- other higher level features can come later/never

2021-12-11 19:40 UTC, RealBazou commented on SolastaCommunityExpansion/Features/FeatureDefinitionFeatureSetBuilder.cs
> +            // IMPROVE THIS AND SEARCH FOR FEATURESET TYPE... THERE IS NO SETTER FOR FEATURESET
This is terrible, I know. How do we do this cleanly?

2021-12-11 23:06 UTC, RedOrcaCode commented on SolastaCommunityExpansion/Features/FeatureDefinitionFeatureSetBuilder.cs
> +            // IMPROVE THIS AND SEARCH FOR FEATURESET TYPE... THERE IS NO SETTER FOR FEATURESET
I recently added a generic FeatureDefinitionBuilder that accepts any FeatureDefinition (including FeatureDefinitionFeatureSet). That way, we don't have to make a new builder for every FeatureDefinition we end up using.

Here's an example of me using it to make a FeatureDefinitionFeatureSet for Path of the Light:

https://github.com/ChrisPJohn/SolastaCommunityExpansion/blob/53139a743ccde604d0486069b84264c7f807af23/SolastaCommunityExpansion/Subclasses/Barbarian/PathOfTheLight.cs#L90-L117

The important part is using SetField to initialize the list of features. I wouldn't exactly call that "clean", but it's our best option at the moment.

2021-12-12 08:27 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Witch.cs
> +                var effectForm = new EffectForm();
FYI There is an EffectFormBuilder in the SolastaModApi which could help here.

2021-12-12 08:27 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Witch.cs
> +                Definition.EffectDescription.Copy(DatabaseHelper.SpellDefinitions.ConjureAnimalsOneBeast.EffectDescription);
FYI There is a EffectDescriptionBuilder in the SolastaModApi which could help here.

2021-12-12 08:27 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Witch.cs
> +        internal class FindFamiliarSpellBuilder : BaseDefinitionBuilder<SpellDefinition>
FYI There is a SpellBuilder in the SolastaModApi which could help here.

2021-12-12 08:27 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Witch.cs
> +                Definition.SetRitual(true);
You mentioned being able to summon infinite familiars. You probably want to use:

Definition.SetUniqueInstance(true);

I've written very few spells, but the similar setting for powers does what you want.

2021-12-12 08:27 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            witch.AddEquipmentRow(  new List<CharacterClassDefinition.HeroEquipmentOption>
You mentioned wanting to use the dropdowns for equipment selection. I think you want something like:

```
List<HeroEquipmentOption> simpleWeaponList = new List<HeroEquipmentOption>();
            HeroEquipmentOption simpleWeaponOption = EquipmentOptionsBuilder.Option(DatabaseHelper.ItemDefinitions.Mace, EquipmentDefinitions.OptionWeaponSimpleChoice, 1);
            simpleWeaponList.Add(simpleWeaponOption);
            simpleWeaponList.Add(simpleWeaponOption);
            ArtificerBuilder.AddEquipmentRow(simpleWeaponList);

List<HeroEquipmentOption> focus = new List<HeroEquipmentOption>
            {
                EquipmentOptionsBuilder.Option(DatabaseHelper.ItemDefinitions.ArcaneFocusWand, EquipmentDefinitions.OptionArcaneFocusChoice, 1)
            };
            ArtificerBuilder.AddEquipmentRow(focus);
```

2021-12-12 08:27 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            // TODO: Simply buff the familiar accordingly, i.e. offer more forms, and if that is too hard,
I don't think we have a way to change the effects of a spell based on caster level currently, but theoretically that's a feature we could add.

That said, it is possible to have summoned creatures advance with the summoner level. This was added for the Kindred Spirits Druid. @DubhHerder is more familiar with that than me and might have some useful advice.

2021-12-12 08:27 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            // TODO: Maledictions should now apply a debuff for disadvantage on saving throw like Force Of Law
I don't know if this is what you're looking for, but possibly the new custom feature to have additional effects on attack hit would be of use:

https://github.com/ChrisPJohn/SolastaCommunityExpansion/blob/Dev/SolastaCommunityExpansion/CustomFeatureDefinitions/FeatureDefinitionOnAttackHitEffect.cs#L25

You can see it used:
https://github.com/ChrisPJohn/SolastaCommunityExpansion/blob/Dev/SolastaCommunityExpansion/Feats/ElAntoniousFeats.cs#L43

I don't know if this supports saving throw based effects, I'd have to go dig through the game code to check. We can probably do something similar for those if needed.

2021-12-12 10:16 UTC, DubhHerder commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            // TODO: Simply buff the familiar accordingly, i.e. offer more forms, and if that is too hard,
There is a limited way to change the effects of a spell based on caster level but it only has a set list of options designed to change the direct effect rather than change the buff a summons so it's not really applicable here as Chris says.

FeatureDefinitionSummoningAffinity is the method to buff summons with with PC level, i'm not sure if its class level or character level by applying conditions to summons with a specified tag. the conditions are used to apply features that could be normal features or that could use the summoners stats to determine the buff. Theres no option to increase via proficiency bonus, the summoner based options are   SourceHalfHitPoints,  SourceSpellCastingAbility, SourceSpellAttack.

so you could have the normal spell to summon a creature at low levels then later add a FeatureDefinitionSummoningAffinity to the summoner class at a higher level that grants an extra attack or improve the creatures to hit, damage, ac, hp etc based on the above, provided the summons has specified tag etc

2021-12-12 10:21 UTC, DubhHerder commented on SolastaCommunityExpansion/Models/SubclassesContext.cs
> +            LoadSubclass(new BloodWitch());
i agree that is likely to be confusing and might result in false bug reports. loading subclasses related to a new class dont need to follow the same template as loading subclasses related to existing classes

2021-12-13 14:47 UTC, RealBazou commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            // BUG: this will not work if applied at level 1, since not all data structures are built before choosing features.
It was failing to apply, so perhaps I was doing something wrong. I'll try to see maybe how Clerics do it?

2021-12-13 15:26 UTC, RealBazou commented on SolastaCommunityExpansion/Classes/Witch.cs
> +                Definition.SetRitual(true);
I have fixed this indeed by adding 
                Definition.SetUniqueInstance(true);

2021-12-14 07:16 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            // How to add an auto-prepared spell if the class has not been instanciated? the caster definition doesn't exist yet
You should be able to add prepared spells. I've done it in Tinkerer. Here's an example in one of the CE subclasses:

https://github.com/ChrisPJohn/SolastaCommunityExpansion/blob/Dev/SolastaCommunityExpansion/Subclasses/Ranger/Arcanist.cs#L71-L101

Note you don't need to use a feature set, you should just be able to do `witch.AddFeatureAtLevel(preparedSpells, 2);`

2021-12-14 20:22 UTC, RealBazou commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            // How to add an auto-prepared spell if the class has not been instanciated? the caster definition doesn't exist yet
I'm sorry, maybe I don't understand well. Apologies if this is the case.
I see the Arcanist Ranger uses DatabaseHelper.CharacterClassDefinitions.Ranger for its ClassDefinition, but in the case of a brand new class like Witch, how can we use the .SetCharacterClass function from the builder if this setup is being done while we are building up the class and before it has been added in the db/instanciated?

2021-12-14 21:05 UTC, ThyWoof commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            // How to add an auto-prepared spell if the class has not been instanciated? the caster definition doesn't exist yet
check https://github.com/ThyWoof/SolastaUnfinishedBusiness/blob/master/SolastaUnfinishedBusiness/ClassWarlock/ClassWarlockBuilder.cs and try something similar... @ChrisPJohn and @DubhHerder are way more knowledgeable in this area. All I did was copy and paste some of their code there.

2021-12-14 22:37 UTC, ThyWoof commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            // How to add an auto-prepared spell if the class has not been instanciated? the caster definition doesn't exist yet
check https://github.com/ThyWoof/SolastaUnfinishedBusiness/blob/master/SolastaUnfinishedBusiness/ClassWarlock/ClassWarlockBuilder.cs and try something similar... @ChrisPJohn and @DubhHerder are way more knowledgeable in this area. All I did was copy and paste some of their code there.

2021-12-18 02:37 UTC, RealBazou commented on SolastaCommunityExpansion/Features/FeatureDefinitionFeatureSetBuilder.cs
> +            // IMPROVE THIS AND SEARCH FOR FEATURESET TYPE... THERE IS NO SETTER FOR FEATURESET
Got rid of this permanently. Proceeded to clear and add.

2021-12-18 02:37 UTC, RealBazou commented on SolastaCommunityExpansion/Models/SubclassesContext.cs
> +            LoadSubclass(new BloodWitch());
Removed all witch subclasses from the subclass settings screen.

2021-12-18 02:38 UTC, RealBazou commented on SolastaCommunityExpansion/Patches/Cheats/RulesetCharacterHeroPatcher.cs
> +                case ExtraRitualCasting.Known:
This was changed by Phil AFAIK. Thank you Phil.

2021-12-18 02:38 UTC, RealBazou commented on SolastaCommunityExpansion/Level20/Classes/WitchBuilder.cs
> +/*using SolastaCommunityExpansion.Level20.Features;
Removed the useless file. Now everything is in the witch class.

2021-12-18 02:39 UTC, RealBazou commented on SolastaCommunityExpansion/Models/ClassesContext.cs
> +        public static Dictionary<string, AbstractClass> Classes = new Dictionary<string, AbstractClass>();
I kept it as is for now, will defer to everyone if this is to be changed or not.

2021-12-18 02:40 UTC, RealBazou commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            // TODO: Do some powers like the Tinkerer infusions, dropdown like infusions too
I am now using FeatureSets whenevr I need them. SharedPool is not what I am looking for (Witch powers do not have a limited amount), but thanks for the tip!

2021-12-18 02:41 UTC, RealBazou commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            // BUG: this will not work if applied at level 1, since not all data structures are built before choosing features.
So this one is still outstanding for me, and I will simply leave it in the pile of known issues for now.

2021-12-18 02:42 UTC, RealBazou commented on SolastaCommunityExpansion/Classes/Witch.cs
> +                var effectForm = new EffectForm();
I have started using the API for this, but I find that sometimes it's easier for me to work from a copy that I want to edit surgically. The API sadly doesn't cover every attribute. I'm trying to use them as much as I can without creating overhead.

2021-12-18 02:42 UTC, RealBazou commented on SolastaCommunityExpansion/Classes/Witch.cs
> +                Definition.EffectDescription.Copy(DatabaseHelper.SpellDefinitions.ConjureAnimalsOneBeast.EffectDescription);
Same as above, I have started using the API for this, but I find that sometimes it's easier for me to work from a copy that I want to edit surgically. The API sadly doesn't cover every attribute. I'm trying to use them as much as I can without creating overhead.

2021-12-18 02:43 UTC, RealBazou commented on SolastaCommunityExpansion/Classes/Witch.cs
> +        internal class FindFamiliarSpellBuilder : BaseDefinitionBuilder<SpellDefinition>
Again, I have started using the API for this, but I find that sometimes it's easier for me to work from a copy that I want to edit surgically. The API sadly doesn't cover every attribute. I'm trying to use them as much as I can without creating overhead.

2021-12-18 02:43 UTC, RealBazou commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            witch.AddEquipmentRow(  new List<CharacterClassDefinition.HeroEquipmentOption>
Thank you, this is now solved!

2021-12-20 17:17 UTC, DubhHerder reviewed
You could try something like 


```using UnityEngine.AddressableAssets;

AssetReference assetReference = new AssetReference();
assetReference.SetField("m_AssetGUID", "763a4e34178a3224d9af53048f4a3e60");     spell.EffectDescription.EffectParticleParameters.SetTargetParticleReference(assetReference);
```
or maybe 
```
spell.EffectDescription.EffectParticleParameters.SetTargetParticleReference(new assetReference("763a4e34178a3224d9af53048f4a3e60"));
```
havent tested the code to confirm it works but it should be close.

2021-12-21 01:53 UTC, RealBazou commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            // TODO: Simply buff the familiar accordingly, i.e. offer more forms, and if that is too hard,
Where is the method that does calculation for the enum? I couldn't find anything for this:
  public enum OriginOfAmount
  {
    None,
    SourceDamage,
    SourceGain,
    AddDice,
    Fixed,
    SourceHalfHitPoints,
    SourceSpellCastingAbility,
    SourceSpellAttack,
  }
Extending this could be really convenient

2021-12-21 02:05 UTC, RealBazou commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            // TODO: Simply buff the familiar accordingly, i.e. offer more forms, and if that is too hard,
A questionable way of getting proficiency bonus would be to somehow do SourceSpellAttack - SourceSpellCastingAbility.
Also, getting the class/character level would be great.

2021-12-21 08:25 UTC, DubhHerder commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            // TODO: Simply buff the familiar accordingly, i.e. offer more forms, and if that is too hard,
ApplySummonForm in RulesetImplementationManagerLocation.cs
If you're having trouble finding a particular piece of code, have you tried indexing code you've decompiled. 

For this particular case, yeah OriginOfAmount could be extended but the current options are reasonable approximations for 5xcharacter level and pb. I did a rough comparison when I was looking at it in the past

2021-12-22 15:53 UTC, RealBazou commented on SolastaCommunityExpansion/Patches/ExtraSummoningModifiers/RulesetImplementationManagerLocation.cs
> +using System.Collections.Generic;
I am unsure why, but spells that summon an item, like Goodberry or Produce Flame (Hold Flame) make the game crash. The prefix implementation is as follows:
- copied the entire code of the method
- added some cases in the switch case, using extended enum values
- used local vars for 
                var dummyCharacterList = new List<GameLocationCharacter>(); 
                var dummySizesList = new List<RulesetActor.SizeParameters>(); 
                var placementPositions = new List<int3>();
                var emptyFormationPositions = new List<int3>();
 since those were private members of the class, without a getter. I searched to see if this is used anywhere else in the class, but nothing came up.

2021-12-22 16:08 UTC, RealBazou commented on SolastaCommunityExpansion/Patches/ExtraSummoningModifiers/RulesetImplementationManagerLocation.cs
> +            rulesetImplementationManager.ApplySummonForm(effectForm, formsParams);
I suspect the crash is here. How does one call the base class inside of a prefix method?

2021-12-22 16:28 UTC, PhilPJL commented on SolastaCommunityExpansion/Patches/ExtraSummoningModifiers/RulesetImplementationManagerLocation.cs
> +            rulesetImplementationManager.ApplySummonForm(effectForm, formsParams);
You can't because ApplySummonForm is a virtual method.

Because RulesetImplementationManagerLocation.ApplySummonForm does this
![image](https://user-images.githubusercontent.com/271656/147123931-1aa7865b-d417-47bf-874e-07ab62a7471d.png)
If your parameters have the appropriate values in them you would end up calling base.ApplySummonForm.

Also, RulesetImplementationManager.ApplySummonForm only acts on it's parameters.  It may as well be a static method.  You can do this
`new RulesetImplementationManager().ApplySummonForm(effectForm, formsParams);`
if it's appropriate.

How can we repro your crash.  It should be obvious in the debugger.

2021-12-22 16:50 UTC, RealBazou commented on SolastaCommunityExpansion/Patches/ExtraSummoningModifiers/RulesetImplementationManagerLocation.cs
> +            rulesetImplementationManager.ApplySummonForm(effectForm, formsParams);
I have attempted using a "ReversePatch" as documented here: https://harmony.pardeike.net/articles/patching-edgecases.html#calling-base-methods
It appears to work, however I am unsure if this is the correct approach. I am definitely not in my element here.

2021-12-22 17:27 UTC, RealBazou commented on SolastaCommunityExpansion/Patches/ExtraSummoningModifiers/RulesetImplementationManagerLocation.cs
> +            rulesetImplementationManager.ApplySummonForm(effectForm, formsParams);
It was possible to reproduce the crash by using the Goodberry spell or Produce Flame -> Hold the Flame

2021-12-23 07:38 UTC, ChrisPJohn requested changes
I'm still working my way through. There's a lot in here. I'll do more tomorrow. Here's a few comments though.

2021-12-23 07:38 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Helpers/Extensions.cs
> +        Known = 1337
Is there a reason leet was chosen for the number here and below? Is it just something high enough that the official TA enums are unlikely to reach that number?

2021-12-23 07:38 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Models/PowersContext.cs
> +        public static string GeneratePowersDescription()
So these strings are designed to be used in the generation of the nexus mod description. You can add them similar to how the feats and subclasses are done here (this comment also applies to spells and classes):

https://github.com/ChrisPJohn/SolastaCommunityExpansion/blob/Dev/SolastaCommunityExpansion/Viewers/HelpAndCreditsViewer.cs#L68-L73

2021-12-23 07:38 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Powers/BazouPowers.cs
> +        private static FeatureDefinitionPower BuildHelpAction()
Maybe I missed it somewhere, but should all characters be given this power?

2021-12-24 08:27 UTC, ChrisPJohn requested changes

2021-12-24 08:27 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/ExtraSummoningModifiers/RulesetImplementationManagerLocation.cs
> +using System.Collections.Generic;
So if I understand this patch you want to calculate sourceAmount differently than the existing enum options do. I'm not a fan of a prefix that entirely replaces the method because that could cause issues for other mods/patches as well as be difficult to maintain with future game patches.

There are two alternative approaches:
1) Use a transpiler (https://harmony.pardeike.net/articles/patching-transpiler.html) @ThyWoof is more familiar with these than me.
2) Use a prefix patch on ApplySummonForm to calculate the sourceAmount and then store that. Then also add a prefix patch on characterMonster.InflictCondition that uses the stored value instead of the parameter.

I'm probably not explaining 2 well here, but something similar to what was done here:
First patch store a value: https://github.com/ChrisPJohn/SolastaCommunityExpansion/blob/843b77a15025e298497720c3a12fce2707f88706/SolastaCommunityExpansion/Patches/GameUiCharactersPanel/CharacterEditionScreenPatcher.cs#L14-L21
Second patch, if value is set, use it: https://github.com/ChrisPJohn/SolastaCommunityExpansion/blob/0f588f62fa7aece847c9ede2b8dedc0aaea1829e/SolastaCommunityExpansion/Patches/GameUiCharactersPanel/CharactersPanelPatcher.cs#L24-L28

2021-12-24 08:27 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Witch.cs
> +// Can we add a Condition dynamically? i.e. can we detect what kind of condition a creature has, and then add that condition here?
There is a feat that adds a condition conditionally:

https://github.com/ChrisPJohn/SolastaCommunityExpansion/blob/Dev/SolastaCommunityExpansion/Feats/ElAntoniousFeats.cs#L41-L72

That is a little bit different that what you're describing, and I'm unsure if that code is triggered on an attack/power that doesn't cause damage. It also doesn't know what attack/spell/power triggered the hit at that point. I have been contemplating a more general CustomEffectForm that could be used to make powers/spells more flexible, but we don't have an implementation yet (partially because we haven't come across something that truly needed it yet).

2021-12-24 08:27 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/AbstractClass.cs
> +        internal abstract void BuildClassStats(CharacterClassDefinitionBuilder classBuilder);
These seem like private methods. As far as I can tell there's no need for anything outside of the Class to need to call these. If that's the case they shouldn't be in the AbstractClass.

2021-12-24 08:27 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Spells/BazouSpells.cs
> +        public static void CreateSpells(List<SpellDefinition> spells)
Should any of these spells be added to spell lists for other classes?

2021-12-24 08:51 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Witch.cs
> +// Can we add a Condition dynamically? i.e. can we detect what kind of condition a creature has, and then add that condition here?
And I threw together a quick prototype of custom effect forms:

https://github.com/ChrisPJohn/SolastaCommunityExpansion/pull/293

I haven't tested it at all, but it should support what you're looking to do with adding a condition dynamically.

2021-12-24 16:37 UTC, RealBazou commented on SolastaCommunityExpansion/Classes/AbstractClass.cs
> +        internal abstract void BuildClassStats(CharacterClassDefinitionBuilder classBuilder);
No problem I can remove them. My reasoning was that every class will need to define these, so I included them do sd to be defined in each class. I'll define them as private.

2021-12-24 16:56 UTC, RealBazou commented on SolastaCommunityExpansion/Helpers/Extensions.cs
> +        Known = 1337
It was to be high enough as to not impede on TA values, and having to pick a number, I chose an eye-rollingly dumb and ironic one. We can change this to something more appropriate.

2021-12-24 17:09 UTC, RealBazou commented on SolastaCommunityExpansion/Powers/BazouPowers.cs
> +        private static FeatureDefinitionPower BuildHelpAction()
In theory, yes, but I didn't want to impede on anyone's code, and I wasn't sure if this is the correct approach. I added it for the Witch class, but in theory, this should be in the default set of actions a character can have. This, and the missing grapple action.

2021-12-24 17:10 UTC, RealBazou commented on SolastaCommunityExpansion/Spells/BazouSpells.cs
> +        public static void CreateSpells(List<SpellDefinition> spells)
I'll check the official list in the book, but I think some classes should be getting these spells as well, yes. I'm not sure how to add these though. A bit like the Help action above, I'm not sure what is the correct approach to do this well.

2021-12-24 17:18 UTC, RealBazou commented on SolastaCommunityExpansion/Spells/BazouSpells.cs
> +        public static void CreateSpells(List<SpellDefinition> spells)
- Eldritch Orb: Warlock
- Find Familiar: Wizard
- Frenzy: Bard, Wizard
- Minor Lifesteal: Sorcerer, Wizard
- Petal Storm: Druid
- Protect Threshold: Sorcerer, Wizard

2021-12-25 06:12 UTC, DubhHerder commented on SolastaCommunityExpansion/Spells/BazouSpells.cs
> +// How can I get an Asset Reference if it is a GameObject loaded in the DB?
Moved this comment because it was misplaced when initially added. 

You could also use the asset reference guids from the blueprints


```using UnityEngine.AddressableAssets;

AssetReference assetReference = new AssetReference();
assetReference.SetField("m_AssetGUID", "763a4e34178a3224d9af53048f4a3e60");     spell.EffectDescription.EffectParticleParameters.SetTargetParticleReference(assetReference);
```
or 
```
spell.EffectDescription.EffectParticleParameters.SetTargetParticleReference(new assetReference("763a4e34178a3224d9af53048f4a3e60"));
```
The previous solution is probably better, this is included for completeness

2021-12-26 17:58 UTC, RealBazou commented on SolastaCommunityExpansion/Subclasses/Witch/WhiteWitch.cs
> +        internal override CharacterSubclassDefinition GetSubclass()
Removed in commit 6d543dc64afc57d98519eb34d93f765d210c795b: https://github.com/ChrisPJohn/SolastaCommunityExpansion/pull/206/commits/6d543dc64afc57d98519eb34d93f765d210c795b

2021-12-26 21:59 UTC, ThyWoof commented on SolastaCommunityExpansion/Spells/BazouSpells.cs
> +        public static void CreateSpells(List<SpellDefinition> spells)
I can help here. Will start thinking on an UI for that

2021-12-27 04:35 UTC, RealBazou commented on SolastaCommunityExpansion/Spells/BazouSpells.cs
> +// How can I get an Asset Reference if it is a GameObject loaded in the DB?
I have tried using the following:
`            // While the Game Object is set correctly, the particle effect doesn't show. 
            spell.EffectDescription.EffectParticleParameters.SetTargetParticleReference(DatabaseHelper.SpellDefinitions.ConjureAnimalsOneBeast.EffectDescription.EffectParticleParameters.GetField<UnityEngine.AddressableAssets.AssetReference>("targetParticleReference"));
`
The object was correctly set, however I didn't get the effect I was hoping for, i.e. the "summoning" particle on the floor. I tried changing the target type to "position", and then I do get that particle, but then I wouldn't get the Spike Growth particle itself. I finally decided to leave it as is, i.e. Sphere target type, with a size of 0, i.e. a weird "dot" that targets a grid square.

2021-12-27 05:17 UTC, RealBazou commented on SolastaCommunityExpansion/Subclasses/Witch/WhiteWitch.cs
> +                                    new List<SpellDefinition>{
I have fixed this and followed the standard for multiclass.

2021-12-27 05:18 UTC, RealBazou commented on SolastaCommunityExpansion/Models/PowersContext.cs
> +        public static string GeneratePowersDescription()
I have added the strings in the HelpAndCreditsViewer file, following the same pattern as Feats.

2021-12-27 06:28 UTC, ChrisPJohn requested changes
Several small things like adding todos or issues to document future work. My main concern though is the patch in RulesetImplementationManagerLocation.cs. I'd like to see something less likely to cause maintenance issues in the future and conflicts with other mods.

I do wonder if we can get the desired effect with a prefix on ApplySummonForm to calculate the sourceAmount for the new cases and then a prefix on InflictCondition that replaces the sourceAmount with our precalculated amount.

2021-12-27 06:28 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Spells/BazouSpells.cs
> +        public static void CreateSpells(List<SpellDefinition> spells)
Can we add either a todo here or an issue to the github repository about making these spells available to other classes?

2021-12-27 06:28 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Witch.cs
> +            classSpellCast.SetKnownCantrips(new List<int>{
I believe you could use some helper functions to simplify this section:

```
classSpellCast.SetKnownCantrips(4, 1, CasterProgression.FULL_CASTER);
classSpellCast.SetKnownSpells(2, 1,  CasterProgression.FULL_CASTER);
classSpellCast.SetSlotsPerLevel(1,  CasterProgression.FULL_CASTER);

```

This is optional to change, but since it looks like your following the standard spell progression I just wanted to call out the helper functions that help make this simpler for you.

2021-12-27 06:28 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Powers/BazouPowers.cs
> +        private static FeatureDefinitionPower BuildHelpAction()
Can we add either a todo here to add this to characters or an issue in the repository?

2021-12-31 07:04 UTC, ChrisPJohn approved these changes

2022-01-01 03:07 UTC, merged