UI to support new classes
ChrisPJohn/SolastaCommunityExpansion pull request #304
Opened 2021-12-27 04:36 UTC by ThyWoof

this one is following the same pattern as subclasses, feats, etc

2021-12-27 04:39 UTC, ThyWoof commented
had to closed previous one as messed up with a merge. followed your idea to make it dynamic @ChrisPJohn .

2021-12-27 05:58 UTC, ChrisPJohn requested changes
I think we can simplify things by just storing the class definition instead of an AbstractClass.

I did an abstract class for subclasses because it needed multiple pieces of information which the full classes don't.

2021-12-27 05:58 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Models/ClassesContext.cs
> +        public static Dictionary<string, AbstractClass> Classes { get; private set; } = new Dictionary<string, AbstractClass>();
Why not make this <string, CharacterClassDefinition>, and then we can get rid of the AbstractClass and just need to have the class declaration provide the CharacterClassDefinition somehow.

2021-12-27 12:45 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/ClassesContext.cs
> +        public static Dictionary<string, AbstractClass> Classes { get; private set; } = new Dictionary<string, AbstractClass>();
Because we're the kings of copy-n-paste ;-). Seriously I would rather keep as is so we can generalize the UI code at some point. Classes, Subclasses, Feats and Fighting Styles all use exactly the same logic. We should at some point a generic interface we can pass to an UI generic display method.

2021-12-28 05:26 UTC, ChrisPJohn approved these changes

2021-12-28 05:26 UTC, merged