better interface for NegativeFeatureBuilder / support for subclasses
ChrisPJohn/SolastaCommunityExpansion pull request #306
Opened 2021-12-27 12:37 UTC by ThyWoof

2021-12-27 12:39 UTC, ThyWoof commented
wrote these changes based on @ChrisPJohn's comments on last merge. It now has support for removal of features in sub classes and no more passing Tag strings. It's now encapsulated and using AttributeDefinitions static methods to derive.

2021-12-27 12:42 UTC, ThyWoof commented
I also changed the suffix on Thug from Remove to ThugRemove. This ensures others can remove same Rogue feature without name colide. Would it be better to pass the original class or subClass holding the removal feature instead of a name, guid tuple? Do the calculation inside by setting name = FeatureToRemove.Name + OwnerClassOrSubClass.Name + "Remove"?

2021-12-28 05:08 UTC, ChrisPJohn requested changes

2021-12-28 05:08 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Subclasses/Rogue/Thug.cs
> +            var featureName = AdditionalDamageRogueSneakAttack.Name + "ThugRemove";
It's bad practice to rename features that are out in users' saved games. I understand that technically since this feature only does something at level up it's unlikely to have any negative effects on users (except error logs when they load), so we can rename if you think it's really important.

2021-12-28 05:08 UTC, ChrisPJohn commented on SolastaCommunityExpansion/CustomFeatureDefinitions/NegativeFeature.cs
> +        public NegativeFeatureBuilder(string name, string guid, FeatureDefinition featureToRemove, int classLevel, CharacterClassDefinition characterClass, CharacterSubclassDefinition characterSubcla
So the benefit is you don't need to know how the tags are generated, but now you need to provide a lot more information.

I think we should add a comment explaining this is the level/class/subclass that the feature you're removing was granted.

2021-12-28 05:33 UTC, ThyWoof commented on SolastaCommunityExpansion/CustomFeatureDefinitions/NegativeFeature.cs
> +        public NegativeFeatureBuilder(string name, string guid, FeatureDefinition featureToRemove, int classLevel, CharacterClassDefinition characterClass, CharacterSubclassDefinition characterSubcla
comment added and also renamed the Feature to a better naming convention.

2021-12-28 05:34 UTC, ThyWoof commented on SolastaCommunityExpansion/Subclasses/Rogue/Thug.cs
> +            var featureName = AdditionalDamageRogueSneakAttack.Name + "ThugRemove";
good call and no need to rename. we should keep an eye though so in the future we adopt a better naming convention if we reuse this feature in other sub classes

2021-12-28 06:07 UTC, ChrisPJohn approved these changes

2021-12-28 06:20 UTC, merged