make class display available now
ChrisPJohn/SolastaCommunityExpansion pull request #353
Opened 2021-12-31 23:47 UTC by ThyWoof

2022-01-01 04:08 UTC, ThyWoof commented
. Some code clean up after Witch merge
. Standardization of custom Feature Definition names
. Added toggle for Help Power

2022-01-01 09:30 UTC, ChrisPJohn reviewed
I'm not adding comments here about classes/subclasses/spell lists since we talked elsewhere about it.

2022-01-01 09:30 UTC, ChrisPJohn commented on SolastaCommunityExpansion/CustomFeatureDefinitions/FeatureDefinitionAttackDisadvantageAgainstNonSource.cs
> +    public class FeatureDefinitionAttackDisadvantageAgainstNonSource : FeatureDefinition, ICombatAffinityProvider
So I think these renames are fine, since I don't think any new mods are using these outside of CE, but technically these are part of the public API of CE and so could be relied on by others.

2022-01-01 09:30 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Models/PowersContext.cs
> +            if (Main.Settings.AddHelpActionToAllClasses)
I know we only have help right now, but should we make this a list like the other groups, so it can scale?

I know Grapple is on our nice to have feature list. Any more would likely have to be home brew though.

2022-01-01 10:12 UTC, ThyWoof commented on SolastaCommunityExpansion/CustomFeatureDefinitions/FeatureDefinitionAttackDisadvantageAgainstNonSource.cs
> +    public class FeatureDefinitionAttackDisadvantageAgainstNonSource : FeatureDefinition, ICombatAffinityProvider
There is only one modder right now writing a new subclass for CE. Should be safe for now.

2022-01-01 10:13 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/PowersContext.cs
> +            if (Main.Settings.AddHelpActionToAllClasses)
I'm still not sure about how big this one can grow. I can certainly revisit this after we get this initial fix in. Right now we have powers disabled anyways...

2022-01-01 10:32 UTC, ThyWoof commented
There is a small bug setting up the initial state of the expand all button; 
It still lacks the Switch method;
Will work on these on a 2nd request;

2022-01-01 14:57 UTC, ThyWoof commented
Initial select all state fixed, call for Switch ready from UI code
Switch missing last calls to add / remove spell to / from class / subclass

2022-01-01 20:24 UTC, ThyWoof commented
@ChrisPJohn , this should be good to go for spells selection.

2022-01-01 20:52 UTC, ChrisPJohn commented
It's not just about modders working in CE, but any mod could be relying on
this. For example Tinkerer uses the shared pool features. I don't think
anybody is currently using these outside of CE, but if they were it would
break their mod.

On Sat, Jan 1, 2022, 02:12 Paulo Monteiro ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> SolastaCommunityExpansion/CustomFeatureDefinitions/FeatureDefinitionAttackDisadvantageAgainstNonSource.cs
> <https://github.com/ChrisPJohn/SolastaCommunityExpansion/pull/353#discussion_r777098496>
> :
>
> > @@ -5,7 +5,7 @@ namespace SolastaCommunityExpansion.CustomFeatureDefinitions
>      /// <summary>
>      /// Imposes disadvantage when attacking anyone but the source of the specified condition.
>      /// </summary>
> -    public class AttackDisadvantageAgainstNonSource : FeatureDefinition, ICombatAffinityProvider
> +    public class FeatureDefinitionAttackDisadvantageAgainstNonSource : FeatureDefinition, ICombatAffinityProvider
>
> There is only one modder right now writing a new subclass for CE. Should
> be safe for now.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ChrisPJohn/SolastaCommunityExpansion/pull/353#discussion_r777098496>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB3E42WNDB3M3MYEFC2JOSLUT3HRPANCNFSM5LB23KHA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because your review was requested.Message ID:
> ***@***.***
> com>
>

2022-01-01 21:15 UTC, ChrisPJohn requested changes
I think having the spells context and settings UI based on class/subclass makes everything more complicated and will confuse users.

It should just be about spell lists.

2022-01-01 21:15 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Models/SpellsContext.cs
> +            internal SpellRecord(SpellDefinition spellDefinition, List<string> suggestedClasses, List<string> suggestedSubclasses)
I still disagree with using class and subclass here and in the UI. It should just be about spell lists.

I think using spell lists directly will be clearer for users and make all of this code simpler.

2022-01-01 21:22 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/SpellsContext.cs
> +            internal SpellRecord(SpellDefinition spellDefinition, List<string> suggestedClasses, List<string> suggestedSubclasses)
Ok. Let me try that

2022-01-01 21:45 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/GuiWrapperContext.cs
> +            var spellDefinitionsMap = AccessTools.Field(guiWrapperService.GetType(), "spellDefinitionsMap").GetValue(guiWrapperService) as Dictionary<string, GuiSpellDefinition>;
Don't forget we have a helper in ModApi so you can write
`guiWrapperService.GetField<x,y>("spellDefinitionsMap")`

2022-01-01 21:47 UTC, PhilPJL commented on SolastaCommunityExpansion/Spells/BazouSpells.cs
> +            SpellsContext.RegisterSpell(BuildEldritchOrb(), new List<string> { "WarlockClass", "ClassWitch" });
Would RegisterSpell benefit from a params parameter?
So you can write

`SpellsContext.RegisterSpell(BuildEldritchOrb(), "WarlockClass", "ClassWitch");`

etc

2022-01-01 21:56 UTC, ThyWoof commented on SolastaCommunityExpansion/Spells/BazouSpells.cs
> +            SpellsContext.RegisterSpell(BuildEldritchOrb(), new List<string> { "WarlockClass", "ClassWitch" });
Agreed and done.

2022-01-01 22:01 UTC, ThyWoof commented
@ChrisPJohn , indeed UI much cleaner now:

![image](https://user-images.githubusercontent.com/13087646/147861045-fbadf8d5-b319-4457-83a2-b97f4dee493a.png)

2022-01-01 22:22 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Models/SpellsContext.cs
> +                var dbCharacterClassDefinition = DatabaseRepository.GetDatabase<CharacterClassDefinition>();
This should be using spell list defintions, not classes.

https://github.com/SolastaMods/SolastaBlueprints/tree/main/SpellListDefinition

2022-01-01 22:25 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Models/SpellsContext.cs
> +        internal static List<CharacterClassDefinition> GetCasterClasses
This should also be by spell list and should support if a subclass (ex Green Mage) defines their own spell list.

2022-01-02 01:40 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/SpellsContext.cs
> +        internal static List<CharacterClassDefinition> GetCasterClasses
ok

2022-01-02 01:48 UTC, ChrisPJohn submitted a review, later dismissed

2022-01-02 01:50 UTC, ThyWoof commented
some sub classes implement CastSpell instead of MagicAffinity... Added that case as well

2022-01-02 01:52 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/147863956-ec6e0057-1f80-447a-9e0e-0c93b1b9b062.png)

2022-01-02 03:52 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/147865658-c129f380-f52c-4bdb-8b48-ef86dbf491d7.png)
3rd screenshot is a charm. now list looks correct.

2022-01-02 08:11 UTC, ChrisPJohn approved these changes

2022-01-02 08:11 UTC, merged