Upcast conjure elemental
ChrisPJohn/SolastaCommunityExpansion pull request #393
Opened 2022-01-04 15:23 UTC by PhilPJL

Stage 1 done and seems to work ok.
Stage 2 is to add CR6 and 7 versions of the fire, air, earth elementals - need some stats

2022-01-04 21:43 UTC, DubhHerder approved these changes
Looks fine to me, especially if it's a quick implementation as noted. One thing that might cause confusion for some users is calling some of the elementals huge when they are still large size creature but that's really minor and doesn't effect implementation. I didn't look at the scaling in terms of balance etc

2022-01-05 08:21 UTC, ChrisPJohn requested changes

2022-01-05 08:21 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Models/UpcastSummonsContext.cs
> +            if (!Main.Settings.EnableUpcastConjureElemental
What's the plan for scaling this to support other summon spells (like fey as the comment states above)? I feel like either the setting should be more general (like EnableUpcastSummoningSpells) or there should be a check for for if the spell is conjure elemental.

2022-01-05 08:21 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Models/UpcastSummonsContext.cs
> +                    Main.Log($"UpcastSummon-ApplySpellLevel: {effectiveLevel}, no suitable upcast - ignoring");
Should this use the highest available? So if the spell is 3rd level and there's upcasts for 4 and 5 but not 6, if I use a 6th level slot I should get the 5th level version.

2022-01-05 09:47 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/UpcastSummonsContext.cs
> +            if (!Main.Settings.EnableUpcastConjureElemental
I change this to just Elementals for now and then rethink when I see what TA finalize for Conjure Fey

2022-01-05 15:35 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/UpcastSummonsContext.cs
> +                    Main.Log($"UpcastSummon-ApplySpellLevel: {effectiveLevel}, no suitable upcast - ignoring");
Good point.

2022-01-05 18:38 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/UpcastSummonsContext.cs
> +                    Main.Log($"UpcastSummon-ApplySpellLevel: {effectiveLevel}, no suitable upcast - ignoring");
Done

2022-01-05 18:38 UTC, PhilPJL commented
Works as is, and I've bumped up the elemental to hit and damage bonus.

2022-01-05 20:22 UTC, DubhHerder reviewed
Just a small note on the monster attack builders

2022-01-05 20:22 UTC, DubhHerder commented on SolastaCommunityExpansion/Builders/MonsterAttackDefinitionBuilder.cs
> +        {
This seems a bit targeted and specific for a builder, if it's included in the builders, maybe the name could mention that it only changes the first effect form damage bonus. It wouldn't work on monster attacks effect descriptions that use any other effect form  in the first entry or effect descriptions with multiple damage entries.

2022-01-05 21:11 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/MonsterAttackDefinitionBuilder.cs
> +        {
I realised that :)  Need something like

```
        public MonsterAttackDefinitionBuilder SetDamageBonus(int value)
        {
            var effectForm = Definition.EffectDescription.GetFirstFormOfType(EffectForm.EffectFormType.Damage);
            effectForm?.DamageForm.SetBonusDamage(value);

            return this;
        }

```

2022-01-05 21:11 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/MonsterAttackDefinitionBuilder.cs
> +        {
I meant to look at what you'd done but forgot.

2022-01-06 11:17 UTC, DubhHerder commented on SolastaCommunityExpansion/Builders/MonsterAttackDefinitionBuilder.cs
> +        {
I did pretty much the same as yourself (copy an existing attack and alter it's parameters) just without the builder as i often wanted to change more than just the first damage bonus entry by adding new effect forms, changing the secondary damage bonuses, die types, damage types etc. 
If i was doing it again, i'd consider using Chris's approach of new effect descriptions etc via the general builders and effectdescription.copy(). 
For reference, here's where i defined monster attacks  but probably not much there you don't already know
https://github.com/ThyWoof/SolastaDungeonMakerPro/blob/master/SolastaDungeonMakerPro/Models/MonsterHelpers/NewMonsterAttacks.cs

2022-01-06 13:10 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/MonsterAttackDefinitionBuilder.cs
> +        {
Ha, I don't know much, I've left all the new monsters, classes etc to Chris and you.

2022-01-07 01:40 UTC, ChrisPJohn approved these changes

2022-01-08 22:57 UTC, PhilPJL commented
Going for subspell filter.

2022-01-08 22:57 UTC, closed without merging