remove extra chars in name patch
ChrisPJohn/SolastaCommunityExpansion pull request #398
Opened 2022-01-05 22:54 UTC by ThyWoof

2022-01-05 22:57 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/GameUiContext.cs
> +        //    public static bool Invoke(TMP_InputField textField)
delete all the commented out code

2022-01-05 22:58 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/GameUiContext.cs
> +        //    public static bool Invoke(TMP_InputField textField)
trailing space isn't a big deal

2022-01-05 22:58 UTC, PhilPJL approved these changes

2022-01-05 23:17 UTC, PhilPJL requested changes
Not sure we can remove - need to check

2022-01-06 01:45 UTC, ThyWoof commented
Ok. Will leave for you to decide and merge.

2022-01-06 15:02 UTC, closed without merging