migrate Level 20 from UB to CE
ChrisPJohn/SolastaCommunityExpansion pull request #43
Opened 2021-11-06 20:49 UTC by ThyWoof

2021-11-06 23:48 UTC, ChrisPJohn requested changes
I think we need to check settings for the patches/transpilers and a few other comments.

2021-11-06 23:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Level20/Classes/PaladinBuilder.cs
> +            AutoPreparedSpellsOathOfDevotion.AutoPreparedSpellsGroups.Add(
You should be able to just add the auto prepared spells groups to the classes existing autoprepared feature

2021-11-06 23:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Level20/Classes/TinkererBuilder.cs
> +            DatabaseRepository.GetDatabase<FeatureDefinitionCastSpell>().TryGetElement("CastSpellTinkerer", out FeatureDefinitionCastSpell featureDefinitionCastSpell);
I'm actually not sure any of this is needed since the TInkerer should be set up for 1-20 already.

2021-11-06 23:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Settings.cs
> +        public bool EnableLevel20 = true;
should this default to false?

2021-11-06 23:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/Level20/UserLocationSettingsModalPatcher.cs
> +                var code = new List<CodeInstruction>(instructions);
I believe the transpilers/patches should be protected by the level 20 enabled setting.

2021-11-06 23:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/Level20/RulesetCharacterHeroPatcher.cs
> +            internal static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
I believe the transpilers/patches should be protected by the level 20 enabled setting.

2021-11-06 23:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/Level20/HigherLevelFeaturesModalPatcher.cs
> +            internal static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
I believe the transpilers/patches should be protected by the level 20 enabled setting.

2021-11-06 23:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Level20/Features/FeatureSetRangerFoeSlayerBuilder.cs
> +﻿//using System;
Can we add a comment explaining the current state of this file? Is it not complete or was there a bug with the implementation?

2021-11-06 23:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Level20/Features/PowerFighterActionSurge2Builder.cs
> +        protected PowerFighterActionSurge2Builder(string name, string guid, int challengeRating) : base(PowerFighterActionSurge, name, guid)
This looks wrong. I assume it's supposed to override the existing action surge and set uses to 2?

2021-11-06 23:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Level20/Classes/TinkererBuilder.cs
> +                featureDefinitionCastSpell.ReplacedSpells.AddRange(SpellsHelper.FullCasterReplacedSpells);
Tinkerer doesn't learn spells, should this be empty?

2021-11-06 23:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/Level20/HeroDefinitionsPatcher.cs
> +                __result = MAX_CHARACTER_EXPERIENCE;
I believe the transpilers/patches should be protected by the level 20 enabled setting.

2021-11-06 23:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/Level20/GameCampaignPartyPatcher.cs
> +                foreach (GameCampaignCharacter characters in __instance.CharactersList)
I believe the transpilers/patches should be protected by the level 20 enabled setting.

2021-11-06 23:48 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/Level20/CharactersPanelPatcher.cs
> +                var code = new List<CodeInstruction>(instructions);
I believe the transpilers/patches should be protected by the level 20 enabled setting.

2021-11-06 23:59 UTC, ThyWoof commented on SolastaCommunityExpansion/Level20/Classes/TinkererBuilder.cs
> +            DatabaseRepository.GetDatabase<FeatureDefinitionCastSpell>().TryGetElement("CastSpellTinkerer", out FeatureDefinitionCastSpell featureDefinitionCastSpell);
will remove this.

2021-11-06 23:59 UTC, ThyWoof commented on SolastaCommunityExpansion/Settings.cs
> +        public bool EnableLevel20 = true;
fixed.

2021-11-06 23:59 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/Level20/HigherLevelFeaturesModalPatcher.cs
> +            internal static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
fixed.

2021-11-07 00:00 UTC, ThyWoof commented on SolastaCommunityExpansion/Level20/Features/FeatureSetRangerFoeSlayerBuilder.cs
> +﻿//using System;
this was written by ElAntonius but requires ModHelpers. will add.

2021-11-07 00:02 UTC, ThyWoof commented on SolastaCommunityExpansion/Level20/Classes/TinkererBuilder.cs
> +                featureDefinitionCastSpell.ReplacedSpells.AddRange(SpellsHelper.FullCasterReplacedSpells);
file removed.

2021-11-07 00:08 UTC, ThyWoof commented on SolastaCommunityExpansion/Level20/Features/PowerFighterActionSurge2Builder.cs
> +        protected PowerFighterActionSurge2Builder(string name, string guid, int challengeRating) : base(PowerFighterActionSurge, name, guid)
Commented this one out for now. Will let you fix as not my forte in the game codebase

2021-11-07 00:08 UTC, ThyWoof commented on SolastaCommunityExpansion/Level20/Classes/PaladinBuilder.cs
> +            AutoPreparedSpellsOathOfDevotion.AutoPreparedSpellsGroups.Add(
not sure if I'm following.

2021-11-07 00:11 UTC, ThyWoof commented on SolastaCommunityExpansion/Level20/Classes/PaladinBuilder.cs
> +            AutoPreparedSpellsOathOfDevotion.AutoPreparedSpellsGroups.Add(
commented out this part of the code for now. This was one of the last changes I made and need help reviewing a better way of doing it.

2021-11-07 04:37 UTC, ChrisPJohn submitted a review, later dismissed

2021-11-07 04:40 UTC, ChrisPJohn approved these changes

2021-11-07 04:40 UTC, merged