fix remaining usage icon display
ChrisPJohn/SolastaCommunityExpansion pull request #496
Opened 2022-01-16 03:03 UTC by ThyWoof

fixes the annoying glitch that kept the remaining time gauge on non light source items.

2022-01-16 03:03 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/149645732-533c67aa-07e3-42eb-b0e7-8159a4e4f8c0.png)

2022-01-16 03:04 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/149645737-087f95ad-04a9-433e-9c1d-68a625f9f23c.png)
yellow icon stays with candle.

2022-01-16 03:06 UTC, ThyWoof commented
these are the first step to try to add a custom icon on top of scrolls that cannot be used => https://github.com/ChrisPJohn/SolastaCommunityExpansion/issues/416

2022-01-16 04:19 UTC, ThyWoof commented
hold merging this one...

2022-01-16 07:10 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/149650821-8bbc3a45-7e30-4032-a1ec-b3f58f29fc81.png)
non-proficient items displayed with a red border

2022-01-16 13:03 UTC, PhilPJL commented
The red border is a great idea, but I think it's being left applied to prefabs, because

First I view this character
![image](https://user-images.githubusercontent.com/271656/149661036-29741f1a-45f1-4d76-930c-a3507a57ca1a.png)

Then this one
![image](https://user-images.githubusercontent.com/271656/149661060-6fdf286b-9c2d-4016-979b-9ed8338e0fcf.png)
None of those were red previously and shouldn't be.

2022-01-16 13:04 UTC, PhilPJL requested changes
Red border issue
Reset to default order issue

2022-01-16 13:05 UTC, PhilPJL commented
If I choose a specific sort order, switch away and back again, the items are in the same order.
If I press 'reset' the sort order is 'default' (whatever that is - random?).  If I switch away and back the items are in a different order.

2022-01-17 01:38 UTC, ThyWoof commented
@PhilPJL : I gave up for now on getting slots with different colors. This fixes the reset button and a cleaner intention in code.

2022-01-17 04:14 UTC, ThyWoof commented
summary for this request:

1. No more glitches on inventory visual effects (i.e.: deity mark, remaining usage, etc.) although game has a bug that will loose these icons if you drag an item;
2. Removed "Requires Restart". One can even flip the Mod UI toggle with the inventory window open (although the controls might be out of sync if one does that. clicking on any control bring them back. no issues even if there are filters enabled and the setting is turned off. No items are lost);
3. Removed the "Reset" button;

2022-01-17 04:15 UTC, ThyWoof commented
ready for another review round @PhilPJL

2022-01-17 09:41 UTC, PhilPJL requested changes

2022-01-17 09:41 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/InventoryManagementContext.cs
> +            SortCategories.ForEach(x => sortOptions.Add(new TMP_Dropdown.OptionData() { text = x }));
Change to use OptionDataAdvanced because of known bugs in DLC.  Can use tooltip if required.

```
            SortCategories.ForEach(x => sortOptions.Add(new OptionDataAdvanced
            {
                text = x,
                //TooltipContent = "<TODO>"
            }));

            SortGuiDropdown.AddOptions(sortOptions);
            SortGuiDropdown.template.sizeDelta = new Vector2(1f, 208f);
            //SortGuiDropdown.UpdateTooltip();
```

2022-01-17 09:41 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/InventoryManagementContext.cs
> +            ItemCategories.ForEach(x => filterOptions.Add(new TMP_Dropdown.OptionData() { text = x.FormatTitle() }));
Change to use OptionDataAdvanced because of known bugs in DLC. Can use tooltip if required.

```
            ItemCategories.ForEach(x => filterOptions.Add(new OptionDataAdvanced
            {
                text = x.FormatTitle(),
                //TooltipContent = "<TODO>"
            }));

            FilterGuiDropdown.AddOptions(filterOptions);
            FilterGuiDropdown.template.sizeDelta = new Vector2(1f, 208f);
            //FilterGuiDropdown.UpdateTooltip();

```

2022-01-17 13:24 UTC, PhilPJL approved these changes

2022-01-17 13:24 UTC, merged