migrate dmpro
ChrisPJohn/SolastaCommunityExpansion pull request #555
Opened 2022-01-22 22:43 UTC by ThyWoof

- migrates all DMPRO features except for custom monsters and multiplayer
- **EnableDungeonMakerPro** is a master hidden switch in the rare case we wanna fully disable this from CE
- **EnableDungeonMakerModdedContent** controls if authors will have access to additional assets in the editor
- **WorldLocationPatcher** is only controlled by the master switch to keep the experience as bug free as possible to players (no need to toggle any switch. all a player requires is install CE to play modded dungeon content)
- custom content in the editor is yellow and tagged as [modded]
- added proper text explaining the consequences of using modded assets in dungeons
- plan is to get support from @DubhHerder to migrate custom monsters from DMPRO

2022-01-22 22:45 UTC, ThyWoof commented
it doesn't make much sense to use builders on **DmProEditorContext.cs**. It would simply make the code more verbose.

2022-01-23 09:25 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/DmProEditorContext.cs
> +        private const string GUID = "bff53ba4bb694bf5a69b3ae280eec118";
maybe change this to
`private static readonly Guid NamespaceGuid = new Guid("...");`
then you eliminate several `new System.Guid(GUID)`

2022-01-23 09:28 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/DmProEditorContext.cs
> +                if (roomBlueprint.Category == "EmptyRooms" || roomBlueprint.Category == "FlatRooms")
Where(...)

2022-01-23 09:29 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/DmProRendererContext.cs
> +            foreach (var prefab in prefabByReference.Values)
FirstOrDefault

2022-01-23 09:32 UTC, PhilPJL commented on SolastaCommunityExpansion/Patches/DungeonMaker/Pro/BaseBlueprintPatcher.cs
> +    internal static class BaseBlueprintPatcher
is this outer class needed?

2022-01-23 09:33 UTC, PhilPJL commented on SolastaCommunityExpansion/Patches/DungeonMaker/Pro/UserLocationSettingsModalPatcher.cs
> +        internal static class UserLocationSettingsModalRefreshVisualMoods
patches not following naming convention elsewhere

2022-01-23 09:34 UTC, PhilPJL requested changes
See comments

2022-01-23 15:49 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/DmProEditorContext.cs
> +        private const string GUID = "bff53ba4bb694bf5a69b3ae280eec118";
fixed

2022-01-23 15:49 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/DmProEditorContext.cs
> +                if (roomBlueprint.Category == "EmptyRooms" || roomBlueprint.Category == "FlatRooms")
fixed

2022-01-23 15:50 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/DmProRendererContext.cs
> +            foreach (var prefab in prefabByReference.Values)
Wouldn't we get an unnecessary call to GetComponentInChildren if we use FirstOrDefault? Inside lambda and then outside if return from FirstOrDefault != null?

2022-01-23 15:51 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/DungeonMaker/Pro/BaseBlueprintPatcher.cs
> +    internal static class BaseBlueprintPatcher
fixed

2022-01-23 15:51 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/DungeonMaker/Pro/UserLocationSettingsModalPatcher.cs
> +        internal static class UserLocationSettingsModalRefreshVisualMoods
fixed

2022-01-23 15:58 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/DmProRendererContext.cs
> +            foreach (var prefab in prefabByReference.Values)
not sure - leave it

2022-01-23 15:58 UTC, PhilPJL approved these changes

2022-01-23 18:30 UTC, merged