Beta cleanup2
ChrisPJohn/SolastaCommunityExpansion pull request #579
Opened 2022-01-27 19:52 UTC by PhilPJL

Started changing List<T> to IEnumerable<T> and params.
This allows us to refactor TinkerSpellList for example.

2022-01-28 08:14 UTC, ChrisPJohn requested changes

2022-01-28 08:14 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Tinkerer/TinkererSpellList.cs
> -            // melee weapon attack (booming blade/green flame blade)
A lot of the comments here were about spells to be added (either if they were included in the game or as additional content in a mod. I'd like to keep that documented somewhere, either in comments here still or as issues.

2022-01-28 08:14 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Tinkerer/FeatureHelpers.cs
> +                Definition.DiceByRankTable.SetRange(diceByRankTable);
I don't think SetRange is guaranteed to have the same behavior as SetValue. This should make sure to fully replace the existing DiceByRankTable.

2022-01-28 08:14 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Classes/Tinkerer/FeatureHelpers.cs
> +                Definition.SetField("featureSet", featureSet.ToList());
Could you highlight the manual changes in this file? I assume this line was manual was, but most of this automated.

Most of this file can probably be just replaced by calls to feature builders already in CE, so I don't particularly want to spend a lot of time reviewing the file.

2022-01-28 09:30 UTC, PhilPJL commented on SolastaCommunityExpansion/Classes/Tinkerer/TinkererSpellList.cs
> -            // melee weapon attack (booming blade/green flame blade)
done

2022-01-28 09:31 UTC, PhilPJL commented on SolastaCommunityExpansion/Classes/Tinkerer/FeatureHelpers.cs
> +                Definition.DiceByRankTable.SetRange(diceByRankTable);
I did check, this field is being initialized. 

```
    [SerializeField]
    [Tooltip("Determines how the number of dice for each rank defined by <damageAdvancement>")]
    private List<DiceByRank> diceByRankTable = new List<DiceByRank>();

```

and SetRange does
```
        public static void SetRange<T>(this List<T> list, IEnumerable<T> range)
        {
            list.Clear();
            list.AddRange(range);
        }

```

2022-01-28 09:39 UTC, PhilPJL commented on SolastaCommunityExpansion/Classes/Tinkerer/FeatureHelpers.cs
> +                Definition.SetField("featureSet", featureSet.ToList());
Most of the changes are manual but some of them I used the change signature refactoring to make the collection parameter the last parameter. Some of them I've used refactorings individually like inline local variable.

2022-01-29 07:29 UTC, ChrisPJohn approved these changes

2022-01-29 09:07 UTC, merged