fix slot types on new foci created items
ChrisPJohn/SolastaCommunityExpansion pull request #725
Opened 2022-02-11 22:11 UTC by ThyWoof

2022-02-11 22:22 UTC, ThyWoof commented
https://github.com/ChrisPJohn/SolastaCommunityExpansion/issues/703

2022-02-12 02:09 UTC, ChrisPJohn requested changes

2022-02-12 02:09 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Models/ItemOptionsContext.cs
> +                EquipmentDefinitions.SlotTypeMainHand,
I don't think we want the amulet to slot into hands.

2022-02-12 02:09 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Models/ItemOptionsContext.cs
>                  ComponentPouch_ArcaneAmulet,
Should this be quarterstaff like the arcane staff above?

2022-02-12 03:37 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/ItemOptionsContext.cs
> +                EquipmentDefinitions.SlotTypeMainHand,
changed builder logic. fixed.

2022-02-12 03:38 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/ItemOptionsContext.cs
>                  ComponentPouch_ArcaneAmulet,
This was in original code when we migrated but makes sense to change to quarterstaff.

2022-02-12 07:23 UTC, ChrisPJohn approved these changes

2022-02-12 13:09 UTC, PhilPJL approved these changes

2022-02-12 13:35 UTC, merged