Additional backstory display
ChrisPJohn/SolastaCommunityExpansion pull request #726
Opened 2022-02-12 05:00 UTC by ThyWoof

2022-02-12 05:00 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/153697418-24e7fe2a-b901-4b79-9a6e-3b4c9f561fa7.png)

2022-02-12 07:25 UTC, ChrisPJohn requested changes

2022-02-12 07:25 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/GameUi/CharacterInspection/GuiCharacterPatcher.cs
> +            builder.Append("\n\n<B>ADDITIONAL BACKSTORY</B>\n\n");
Additional Backstory should be in translations.

2022-02-12 13:10 UTC, PhilPJL commented on SolastaCommunityExpansion/Patches/GameUi/CharacterInspection/GuiCharacterPatcher.cs
> +            builder.Append("\n\n<B>ADDITIONAL BACKSTORY</B>\n\n");
Not sure but is it worth using Environment.Newline instead of \n since the game runs on Linux?  Probably no difference but...

2022-02-12 13:53 UTC, PhilPJL approved these changes

2022-02-14 05:55 UTC, ChrisPJohn approved these changes

2022-02-14 08:20 UTC, merged