Beta standardize builders2
ChrisPJohn/SolastaCommunityExpansion pull request #769
Opened 2022-02-16 12:08 UTC by PhilPJL

Add another version of DefinitionBuilder that takes a TBuilder parameter.  I'm thinking about scripting all builders and this would be required to support that.  Also allows simplification of Configure.
Some refactor.

2022-02-17 01:22 UTC, ThyWoof submitted a review, later dismissed

2022-02-17 01:54 UTC, ChrisPJohn commented
I haven't had a chance to do a thorough review of this and I'd like to.

This is more a comment on the implied direction in the pull comment. I don't know if scripting builders is particularly useful. With extension support for setting all fields and the new configure, it seems the functionality that a scripted builder would provide is covered. The builders previously handled a lot of initialization logic that was needed as well as had some thought put into methods that set fields together which would commonly be set at the same time (like these 3 fields are needed to properly set up a saving throw, so there's a SetSavingThrow method that has those parameters). Automatically created builders are not going to have that.

2022-02-17 05:10 UTC, ChrisPJohn requested changes

2022-02-17 09:00 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerBuilder.cs
> +        public FeatureDefinitionPowerBuilder Configure(
Ok understood.

2022-02-17 09:02 UTC, PhilPJL commented on SolastaCommunityExpansion/Classes/Tinkerer/Subclasses/BattleSmithBuilder.cs
> -            battleSmithPresentation.SetSpriteReference(DatabaseHelper.CharacterSubclassDefinitions.MartialSpellblade.GuiPresentation.SpriteReference);
It looks like there never was one.

2022-02-17 09:05 UTC, PhilPJL commented on SolastaCommunityExpansion/Classes/Tinkerer/Subclasses/BattleSmithBuilder.cs
> -            battleSmithPresentation.SetSpriteReference(DatabaseHelper.CharacterSubclassDefinitions.MartialSpellblade.GuiPresentation.SpriteReference);
Done

2022-02-17 09:11 UTC, PhilPJL commented
> I haven't had a chance to do a thorough review of this and I'd like to.
> 
> This is more a comment on the implied direction in the pull comment. I don't know if scripting builders is particularly useful. With extension support for setting all fields and the new configure, it seems the functionality that a scripted builder would provide is covered. The builders previously handled a lot of initialization logic that was needed as well as had some thought put into methods that set fields together which would commonly be set at the same time (like these 3 fields are needed to properly set up a saving throw, so there's a SetSavingThrow method that has those parameters). Automatically created builders are not going to have that.

My intention - if it's thought worthwhile and I have enough energy - would be to create the complete hierarchy of builders (still haven't got it straight in my head) so may need two instances of each builder type like
    public abstract class FeatureDefinitionFeatureSetBuilder<TDefinition, TBuilder> : DefinitionBuilder<TDefinition, TBuilder>
and
    public class FeatureDefinitionFeatureSetBuilder : FeatureDefinitionFeatureSetBuilder<FeatureDefinitionFeatureSet, FeatureDefinitionFeatureSetBuilder>
I may be overthinking things.

And then have all of the definition setters as private or protected members.
These can be promoted to public as necessary - saves typing - or used in higher level methods.

2022-02-17 09:15 UTC, PhilPJL commented
Apologies.  I thought I had branched to make further changes on top of previous PR.  When I did a push they added to this one.

2022-02-18 06:39 UTC, ChrisPJohn approved these changes

2022-02-18 08:10 UTC, PhilPJL commented
I should have mentioned that if I did create a script this would be used once only not on every release. I'm not sure it's worth creating since we probably have builders for the most used definitions already.

2022-02-18 08:16 UTC, merged