Beta: add some custom extension methods
ChrisPJohn/SolastaCommunityExpansion pull request #784
Opened 2022-02-18 12:20 UTC by PhilPJL

Adding methods for SetRange, SetDuration. Do they make sense?

2022-02-18 16:36 UTC, ThyWoof approved these changes

2022-02-18 20:30 UTC, ThyWoof approved these changes

2022-02-19 06:24 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Builders/EffectDescriptionBuilder.cs
> +        {
Did you see the SetDurationData and SetTargetingData (includes range) above?

2022-02-19 06:24 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Api/AdditionalExtensions/EffectDescriptionExtensions.cs
> +        public static T SetDuration<T>(this T entity, RuleDefinitions.DurationType type, int? duration = null)
Do we want to support methods like this in class extensions or only in the builders? If builders become simply one to one passthroughs to methods added in extensions, the builders aren't adding very much benefit.

2022-02-19 06:24 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Api/AdditionalExtensions/EffectDescriptionExtensions.cs
> +                    entity.SetDurationParameter(0);
I'd go with the default value which (in the last decompile I have) is 1.

2022-02-19 06:24 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Builders/ConditionDefinitionBuilder.cs
> +                    Definition.SetDurationParameter(0);
I'd suggest the default value of 1.

2022-02-19 06:24 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Builders/ConditionDefinitionBuilder.cs
> +        // TODO: is it worth/possible to factor out ConditionDefinitionBuilder.SetDuration and EffectDescriptionBuilder.SetDuration?
Static function that takes an object and checks what type the object is and/or if the appropriate fields exist before setting them?

Alternatively static function to do the validation of the values (it seems the validation here is the biggest chunk of code). If they validate then the builder sets the values on the object.

2022-02-19 06:25 UTC, ChrisPJohn requested changes
Marking request changes for at least the default duration parameter.

2022-02-19 09:21 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/EffectDescriptionBuilder.cs
> +        {
No saw that later after raised the PR.

2022-02-19 09:28 UTC, PhilPJL commented on SolastaCommunityExpansion/Api/AdditionalExtensions/EffectDescriptionExtensions.cs
> +        public static T SetDuration<T>(this T entity, RuleDefinitions.DurationType type, int? duration = null)
ok I'll add a TODO to remove those extensions

2022-02-19 09:37 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/ConditionDefinitionBuilder.cs
> +                    Definition.SetDurationParameter(0);
I don't think the default values are meaningful, e.g.
![image](https://user-images.githubusercontent.com/271656/154795384-d54abb64-b356-4ea3-8fd0-e11f5d3a0c18.png)
I think I'll stick with 0 for these, although the values will be ignored in these cases (if I've got it right).

2022-02-19 09:37 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/ConditionDefinitionBuilder.cs
> +        // TODO: is it worth/possible to factor out ConditionDefinitionBuilder.SetDuration and EffectDescriptionBuilder.SetDuration?
I like the validation idea.

2022-02-19 09:42 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/EffectDescriptionBuilder.cs
> +        {
Will combine in future

2022-02-19 09:43 UTC, PhilPJL commented on SolastaCommunityExpansion/Api/AdditionalExtensions/EffectDescriptionExtensions.cs
> +        public static T SetDuration<T>(this T entity, RuleDefinitions.DurationType type, int? duration = null)
Need to fix various places to use a builder instead of the definition directly

2022-02-19 09:43 UTC, PhilPJL commented on SolastaCommunityExpansion/Api/AdditionalExtensions/EffectDescriptionExtensions.cs
> +                    entity.SetDurationParameter(0);
Sorry sticking with 0 for values which should have no duration/range.

2022-02-19 22:40 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Api/AdditionalExtensions/EffectDescriptionExtensions.cs
> +        public static T SetDuration<T>(this T entity, RuleDefinitions.DurationType type, int? duration = null)
Either path is valid. I was just raising this because I thought one of our goals was to be moving towards more consistency with a single suggested way to do things.

2022-02-19 22:41 UTC, ChrisPJohn approved these changes

2022-02-20 13:39 UTC, merged