Beta square cylinder
ChrisPJohn/SolastaCommunityExpansion pull request #785
Opened 2022-02-18 14:08 UTC by PhilPJL

Implement a 'Square Cylinder' TargetType by patching TargetType.Cube.
If TargetParameter2 != 0 then adjust geometry code to use a square cylinder of height TargetParameter2.

TODO: adjust wire frame drawn showing area of effect after casting the spell

2022-02-18 16:41 UTC, ThyWoof commented
I believe all patterns Prefix / Postfix that set Height can be done with less patches if we transpile the call to `UpdateCubePosition_Regular` within `UpdateGeometricShape`.

2022-02-19 07:13 UTC, ChrisPJohn requested changes
A couple small changes.

For GeometryPatcher I focused on if the code was protected with settings checks and less on the math. I assume I'm unlikely to catch a math error that wasn't caught testing the changes, but also it's late. If you want a thorough math review I can take a look later.

2022-02-19 07:13 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Settings.cs
> +        public bool SquareAreaOfEffectSpellsDoNotAffectFlyingCreatures { get; set; } = true;
This should probably not be set to true by default.

2022-02-19 07:13 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Spells/HouseSpellTweaks.cs
> +/*            static void LogAllSpellsWithTargetTypeCube()
Clean up debug code?

2022-02-19 09:20 UTC, PhilPJL commented on SolastaCommunityExpansion/Spells/HouseSpellTweaks.cs
> +/*            static void LogAllSpellsWithTargetTypeCube()
Removed

2022-02-19 22:43 UTC, ChrisPJohn approved these changes

2022-02-19 23:09 UTC, ThyWoof approved these changes

2022-02-19 23:10 UTC, merged