Beta diagnostics
ChrisPJohn/SolastaCommunityExpansion pull request #805
Opened 2022-02-21 20:10 UTC by PhilPJL

Reworked current Gui presentation and definition diagnostics, and added serialization of all CE definitions to json.

Set the system environment variable 'SolastaCEDiagnosticsDir' to point to you project diagnostics folder, e.g.
"C:\Users\passp\source\repos\SolastaCommunityExpansion\SolastaCommunityExpansion\Diagnostics"

When you run the game all gui presentations and definitions will be saved in 6 files
![image](https://user-images.githubusercontent.com/271656/155020374-adddf4d8-98c4-4508-8526-f5021916d571.png)

If these files have changes you will see them before commit and can then check nothing's fup'ed.

2022-02-21 20:29 UTC, ThyWoof requested changes

2022-02-21 20:29 UTC, ThyWoof commented on SolastaCommunityExpansion/Settings.cs
> +        internal List<string> KnownDuplicateDefinitionNames { get; } = new()
If you make this internal the setting won’t dump to the xml file. It might be useful to tweak the behavior without reconciling. If not the intent then might be better to move this into Diagnostics.

2022-02-21 20:44 UTC, PhilPJL commented on SolastaCommunityExpansion/Settings.cs
> +        internal List<string> KnownDuplicateDefinitionNames { get; } = new()
Yes I know, every time the settings were saved that value was being added.  I had a list of about 50 "SummonProtectorConstruct" in my settings file. Couldn't see how to stop that behaviour.  I can move it for now I guess.

2022-02-21 22:18 UTC, DubhHerder approved these changes
I am not familiar with this type of process so i cant offer much in the way of reviewing other than noting that TA are obviously comfortable having missing translations / guiPresentations so is there a need to track their omissions or us?

2022-02-21 22:24 UTC, PhilPJL commented
> I am not familiar with this type of process so i cant offer much in the way of reviewing other than noting that TA are obviously comfortable having missing translations / guiPresentations so is there a need to track their omissions or us?

Not sure tracking TA's missing translations etc is of any benefit other than we can tell them, although surely they know already? But I quite often see 'Feature/&xyz' in the game so they do need to fix them.

2022-02-21 22:25 UTC, PhilPJL commented on SolastaCommunityExpansion/Settings.cs
> +        internal List<string> KnownDuplicateDefinitionNames { get; } = new()
Done

2022-02-22 03:39 UTC, ThyWoof submitted a review, later dismissed

2022-02-22 08:20 UTC, ChrisPJohn requested changes
Main thing is defaulting this to off for release builds since I assume we don't need this in releases.

2022-02-22 08:20 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Settings.cs
> +        public bool DebugEnableTADefinitionDiagnostics { get; set; } = true;
Should these just be true for debug and false for release?

2022-02-22 08:20 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Diagnostics/CE-Definitions-GuiPresentation-MissingTranslation-en.txt
> +AddConstructCantrips	Title='Feat/&AddConstructCantripsTitle'.
I assume we can use this to track what keys need translations when/if we start supporting localizing CE?

Are we expecting to work on making the en list 0 items or is it ok for stuff to be in here?

2022-02-22 08:32 UTC, PhilPJL commented on SolastaCommunityExpansion/Settings.cs
> +        public bool DebugEnableTADefinitionDiagnostics { get; set; } = true;
I'm going to change those to false and add UI.

2022-02-22 08:33 UTC, PhilPJL commented on SolastaCommunityExpansion/Diagnostics/CE-Definitions-GuiPresentation-MissingTranslation-en.txt
> +AddConstructCantrips	Title='Feat/&AddConstructCantripsTitle'.
This is a hint for use to add translations or change the GUIPresentation to indicate no translation required.

2022-02-22 08:38 UTC, PhilPJL commented on SolastaCommunityExpansion/Settings.cs
> +        public bool DebugEnableTADefinitionDiagnostics { get; set; } = true;
Not sure where to put debug/diagnostics settings @ThyWoof

2022-02-22 09:40 UTC, PhilPJL commented on SolastaCommunityExpansion/Diagnostics/CE-Definitions-GuiPresentation-MissingTranslation-en.txt
> +AddConstructCantrips	Title='Feat/&AddConstructCantripsTitle'.
Some of them will drop out after #810 
Some of them are erroneous because I notice they are explicitly and empty string in translations.txt.  
Need to remove Telema ones
Some like PowerAttackCondition don't have a key, just text - odd?
But the rest should have English entries or should explicitly be Feature/NoContent

2022-02-22 10:09 UTC, PhilPJL commented on SolastaCommunityExpansion/Diagnostics/CE-Definitions-GuiPresentation-MissingTranslation-en.txt
> +AddConstructCantrips	Title='Feat/&AddConstructCantripsTitle'.
I see that TA have "Feature/&Emptystring".  After this and #810 are in, I'll add that and take it into account in diagnostics.

2022-02-24 05:27 UTC, ChrisPJohn approved these changes

2022-02-24 05:44 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Diagnostics/CE-Definitions-GuiPresentation-MissingTranslation-en.txt
> +TraditionSpellMasterSpellResistance	Title='Spell/&TraditionSpellMasterSpellResistanceTitle'.
Just an FYI.

So this looks like a refactoring broke it at some point. TraditionSpellMasterSpellResistanceTitle and description are under Subclass in the translations file (not spell).

I don't know if other entries in here are similar.

2022-02-24 08:20 UTC, PhilPJL commented on SolastaCommunityExpansion/Diagnostics/CE-Definitions-GuiPresentation-MissingTranslation-en.txt
> +TraditionSpellMasterSpellResistance	Title='Spell/&TraditionSpellMasterSpellResistanceTitle'.
I'll check

2022-02-24 08:20 UTC, merged