Game Context Idea
ChrisPJohn/SolastaCommunityExpansion pull request #882
Opened 2022-03-02 04:37 UTC by ThyWoof

@ChrisPJohn , @DubhHerder , @RealBazou  had this idea to patch some key methods in BattleManager (maybe do the same in ActionManager) to get us a context of all parameters passed to these methods. I believe these might make some feature implementations easier...

let's use this request for discussion.

here is an output with the one method I tested so far:

![image](https://user-images.githubusercontent.com/13087646/156295853-e0433d89-c274-4e82-808f-d75fc1a42e47.png)

2022-03-02 19:24 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/156434114-dee64bde-8c1a-40bc-91be-ab762f85481f.png)
using delegates

2022-03-02 21:21 UTC, ThyWoof commented
sample log during combat. features would be able to get context at each one of these:
```
[SolastaCommunityExpansion] [Warning] HandleSpellCast prefix caster: Celia spell: Light
[SolastaCommunityExpansion] [Warning] HandleSpellCast postfix caster: Celia spell: Light
[SolastaCommunityExpansion] [Warning] HandleSpellTargeted prefix caster: Celia defender: Celia
[SolastaCommunityExpansion] [Warning] HandleSpellTargeted postfix caster: Celia defender: Celia
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart prefix mover: Celia destination: int3(31, 0, 21)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart postfix mover: Celia destination: int3(31, 0, 21)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd prefix mover: Celia
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd postfix mover: Celia
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart prefix mover: Celia destination: int3(32, 0, 22)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart postfix mover: Celia destination: int3(32, 0, 22)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd prefix mover: Celia
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd postfix mover: Celia
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart prefix mover: Celia destination: int3(32, 0, 23)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart postfix mover: Celia destination: int3(32, 0, 23)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd prefix mover: Celia
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd postfix mover: Celia
[SolastaCommunityExpansion] [Warning] HandleCharacterAttack prefix attacker: Anton defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterAttack postfix attacker: Anton defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleRangeAttack prefix launcher: Anton target: Bandit
[SolastaCommunityExpansion] [Warning] HandleRangeAttack postfix launcher: Anton target: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterAttackHit prefix attacker: Anton defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterAttackHit postfix attacker: Anton defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterAttackDamage prefix attacker: Anton defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterAttackDamage postfix attacker: Anton defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleReactionToDamageShare prefix damagedCharacter: Bandit damageAmount: 6
[SolastaCommunityExpansion] [Warning] HandleReactionToDamageShare postfix damagedCharacter: Bandit damageAmount: 6
[SolastaCommunityExpansion] [Warning] HandleCharacterAttackFinished prefix attacker: Anton defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterAttackFinished postfix attacker: Anton defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart prefix mover: Bandit destination: int3(33, 0, 23)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart postfix mover: Bandit destination: int3(33, 0, 23)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd prefix mover: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd postfix mover: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart prefix mover: Bandit destination: int3(33, 0, 22)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart postfix mover: Bandit destination: int3(33, 0, 22)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd prefix mover: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd postfix mover: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart prefix mover: Bandit destination: int3(32, 0, 21)
[SolastaCommunityExpansion] [Warning] HandleCharacterAttack prefix attacker: Celia defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterAttack postfix attacker: Celia defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterAttackHit prefix attacker: Celia defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterAttackHit postfix attacker: Celia defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterAttackDamage prefix attacker: Celia defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterAttackDamage postfix attacker: Celia defender: Bandit
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart prefix mover: Acolyte destination: int3(43, 0, 31)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart postfix mover: Acolyte destination: int3(43, 0, 31)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd prefix mover: Acolyte
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd postfix mover: Acolyte
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart prefix mover: Acolyte destination: int3(42, 0, 30)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart postfix mover: Acolyte destination: int3(42, 0, 30)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd prefix mover: Acolyte
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd postfix mover: Acolyte
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart prefix mover: Acolyte destination: int3(41, 0, 29)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart postfix mover: Acolyte destination: int3(41, 0, 29)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd prefix mover: Acolyte
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd postfix mover: Acolyte
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart prefix mover: Acolyte destination: int3(40, 0, 28)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart postfix mover: Acolyte destination: int3(40, 0, 28)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd prefix mover: Acolyte
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd postfix mover: Acolyte
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart prefix mover: Acolyte destination: int3(39, 0, 27)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart postfix mover: Acolyte destination: int3(39, 0, 27)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd prefix mover: Acolyte
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd postfix mover: Acolyte
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart prefix mover: Acolyte destination: int3(38, 0, 26)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveStart postfix mover: Acolyte destination: int3(38, 0, 26)
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd prefix mover: Acolyte
[SolastaCommunityExpansion] [Warning] HandleCharacterMoveEnd postfix mover: Acolyte
[SolastaCommunityExpansion] [Warning] HandleSpellCast prefix caster: Acolyte spell: SacredFlame
[SolastaCommunityExpansion] [Warning] HandleSpellCast postfix caster: Acolyte spell: SacredFlame
[SolastaCommunityExpansion] [Warning] HandleSpellTargeted prefix caster: Acolyte defender: Celia
[SolastaCommunityExpansion] [Warning] HandleSpellTargeted postfix caster: Acolyte defender: Celia
[SolastaCommunityExpansion] [Warning] HandleCharacterMagicalAttackDamage prefix attacker: Acolyte defender: Celia
[SolastaCommunityExpansion] [Warning] HandleCharacterMagicalAttackDamage postfix attacker: Acolyte defender: Celia
[SolastaCommunityExpansion] [Warning] HandleFailedSavingThrowAgainstEffect prefix caster: Acolyte defender: Celia
[SolastaCommunityExpansion] [Warning] HandleFailedSavingThrowAgainstEffect postfix caster: Acolyte defender: Celia
[SolastaCommunityExpansion] [Warning] HandleReactionToDamageShare prefix damagedCharacter: Celia damageAmount: 5
[SolastaCommunityExpansion] [Warning] HandleReactionToDamageShare postfix damagedCharacter: Celia damageAmount: 5
[SolastaCommunityExpansion] [Warning] HandleSpellCast prefix caster: Nialla spell: FireBolt
[SolastaCommunityExpansion] [Warning] HandleSpellCast postfix c [...]

2022-03-02 22:41 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/156462046-143c601a-94f5-45bc-9e38-85f8c39261da.png)
having access to attacker, defender and damageForm here opens lots of possibilities

2022-03-04 07:31 UTC, ChrisPJohn commented
> ![image](https://user-images.githubusercontent.com/13087646/156462046-143c601a-94f5-45bc-9e38-85f8c39261da.png) having access to attacker, defender and damageForm here opens lots of possibilities

Just a note- if I remember this code properly the damage from the damage forms have already been applied (but additional damage hasn't been applied yet).

2022-03-04 08:12 UTC, ChrisPJohn requested changes

2022-03-04 08:12 UTC, ChrisPJohn commented on SolastaCommunityExpansion/CustomFeatureDefinitions/FeatureDefinitionOnAttackHitEffect.cs
>       * better for future maintainability of features to use the features provided by TA.
Just a note that this feature has a comment calling out that it should be used sparingly and only if TA provided features can't accomplish the goal. The reason for that is there's already several feature definitions that are checked in the game code here:
on the attacker: IAdditionalDamageProvider, on attack activated powers
on the defender: IDamageAffinityProvider, checks for reaction powers and other special abilities

I believe most of the other handlers are similar in that there are already TA provided features to hook into the events. I just wanted to draw attention to this before we build a lot of infrastructure to make them all easier to use.

As for why using the custom code features are discouraged if there are other options, they are more likely to cause game slow downs and crashes than using a TA provided feature definition. Additionally they expose the ability to change game state in ways that could cause bugs or instability. Custom code features also allow for much greater flexibility and there are times to use them.

2022-03-04 19:02 UTC, ThyWoof commented
closing this one for now as researching other ideas to better trap these methods

2022-03-04 19:02 UTC, closed without merging