refactor indomitable might and generalize interface
ChrisPJohn/SolastaCommunityExpansion pull request #884
Opened 2022-03-03 05:06 UTC by ThyWoof

* Indomitable Might should change the check result to be equals to the strength attribute current value;
* Code was very specific and only considering this particular case. Changed interface to allow more flexibility for other features;
* There was also a bug report on Nexus about shoves using double bonus and this code was touching `AbilityCheck`;

2022-03-03 06:37 UTC, DubhHerder commented
The double bonus shove bug is limited to a specific monster and is due to the monsters features rather than any issue with the code, as described in issue #590

2022-03-03 12:33 UTC, ThyWoof commented
Thanks @DubhHerder. Anyway this code is much cleaner. It now supports any other attribute

2022-03-03 21:05 UTC, PhilPJL commented on SolastaCommunityExpansion/Patches/CustomFeatures/RulesetCharacterPatcher.cs
> +            var featuresToBrowse = new List<FeatureDefinition>();
could be

```
            var min = rulesetCharacter
                .EnumerateFeaturesToBrowse<IChangeAbilityCheck>()
                .Max(x => x.MinAbilityCheck(rulesetCharacter, baseBonus, rollModifier, abilityScoreName, proficiencyName, advantageTrends, modifierTrends));

            if (result < min)
            {
                result = min;
            }
```

I'll get my extension method used somehow :)

2022-03-03 21:09 UTC, PhilPJL reviewed
It all looks ok, but I'll leave this to Chris.

2022-03-03 21:22 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/CustomFeatures/RulesetCharacterPatcher.cs
> +            var featuresToBrowse = new List<FeatureDefinition>();
Thanks. I didn't like the OfType used again.

2022-03-03 21:23 UTC, ThyWoof commented
@ChrisPJohn , once we get this one checked my next step is to reorganize the custom features folder to simplify matching new features with patches.

2022-03-03 21:25 UTC, PhilPJL commented on SolastaCommunityExpansion/Patches/CustomFeatures/RulesetCharacterPatcher.cs
> +            var featuresToBrowse = new List<FeatureDefinition>();
You can use the extension method as
`EnumerateFeaturesToBrowse<IChangeAbilityCheck>(true)`
to update the rulesetCharacter featuresToBrowse property.  Which you don't want in this case I think.

2022-03-04 07:09 UTC, ChrisPJohn requested changes
Request changes for the CustomCode folder name and to consider the changes to the die roll patches.

2022-03-04 07:09 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/CustomFeatures/ChangeAbilityCheck/RulesetCharacterPatcher.cs
> +    internal static class RulesetCharacter_RollAbilityCheck
Did you consider using a Postfix patch on RollDie to modify the die roll (in this case set to min if it's too low) and capturing context (really just abilityScore is needed for this use case) in prefixes on RollAbilityCheck and ResolveContestCheck?

That would allow for a more general die roll modifier if that's the goal of this change. It would require an additional patch for this feature, but no transpiler.  That approach would also make it possible to implement something like a Clockwork Amulet (modifies attack rolls) with no additional patches.

2022-03-04 08:16 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/CustomFeatures/CustomCode/RulesetCharacterHeroPatcher.cs
> +    internal static class RulesetCharacterHero_TrainFeats
Moved this patch back to top folder and added more comments there.

2022-03-04 08:16 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/CustomFeatures/CustomCode/CharacterBuildingManagerPatcher.cs
> +namespace SolastaCommunityExpansion.Patches.CustomFeatures.CustomCode
This folder ended up with one patch only so moved back to top folder for now.

2022-03-04 08:24 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/CustomFeatures/ChangeAbilityCheck/RulesetCharacterPatcher.cs
> +    internal static class RulesetCharacter_RollAbilityCheck
We cannot do that in RollDie for ability checks due to passive checks as RollDie only gets called if not passive. RollDie also gets called twice on ResolveContestCheck which makes it a bit harder to store the context.

This particular transpiler is replacing method calls which is much safer than looking for a particular code sequence. It's also pushing the arguments from the original methods to the stack vs local variables. The later can be an issue when we deal with debug and production builds (I put warning comments all over the code for these cases, fyi).

We could implement a similar interface on RollDie to allow changing the results and/or parameters to the call.

2022-03-05 05:11 UTC, ChrisPJohn approved these changes

2022-03-05 10:05 UTC, merged