Allow Shift-R to rotate item
ChrisPJohn/SolastaCommunityExpansion pull request #922
Opened 2022-03-10 20:55 UTC by PhilPJL

Tiny QOL.  Allow Shift-R to rotate say a wall-blocker, so when dropping loads of wall blockers can rotate with releasing shift.

2022-03-10 23:20 UTC, ThyWoof requested changes

2022-03-10 23:20 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/GameUiContext.cs
> +            inputService.RegisterCommand(InputCommands.Id.EditorRotate, 114, (int)KeyCode.LeftShift, -1, -1, -1, -1);
Can we use Keycode instead of 114?

2022-03-11 08:46 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/GameUiContext.cs
> +            inputService.RegisterCommand(InputCommands.Id.EditorRotate, 114, (int)KeyCode.LeftShift, -1, -1, -1, -1);
Done

2022-03-11 16:37 UTC, ThyWoof approved these changes

2022-03-11 16:37 UTC, merged