Beta refactor
ChrisPJohn/SolastaCommunityExpansion pull request #938
Opened 2022-03-14 17:56 UTC by PhilPJL

More refactoring.
Mostly LifeTransmuter and SpellMaster.

2022-03-15 08:16 UTC, ChrisPJohn requested changes

2022-03-15 08:16 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerPoolModifierBuilder.cs
> +            Definition.SetActivationTime(RuleDefinitions.ActivationTime.Permanent);
All of these hardcoded values should be set in the constructor. In particular making sure effect description is set and that cost per use is 1 (though really everything that's hardcoded should just be set in the constructor).

2022-03-15 08:16 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerPoolModifierBuilder.cs
> +            Definition.PoolPower = poolPower;
It should not be possible to construct a power pool modifier without providing a pool. I'd prefer either it is required in the constructor or we have validation to make sure it's been set.

2022-03-15 08:16 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerSharedPoolBuilder.cs
> +        public FeatureDefinitionPowerPoolBuilder Configure(int usesPerRecharge,
Similar to other builder changes, I don't like that there is now a way to construct this without some of the values getting set (for example cost per use).

2022-03-15 08:16 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerSharedPoolBuilder.cs
> +        public FeatureDefinitionPowerSharedPoolBuilder Configure(FeatureDefinitionPower poolPower,
I don't like that there is now a path to construct that allows some critical fields (uses determination, shared pool) to not be set.

2022-03-15 08:16 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Subclasses/Wizard/SpellMaster.cs
> +                BonusRecovery
This might need a check that the BonusRecovery has been initialized.

2022-03-15 16:59 UTC, PhilPJL commented on SolastaCommunityExpansion/Subclasses/Wizard/SpellMaster.cs
> +                BonusRecovery
I think all definitions have been created before anyone can view the settings page.

2022-03-15 18:03 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerPoolModifierBuilder.cs
> +            Definition.PoolPower = poolPower;
Added validation

2022-03-16 01:54 UTC, ThyWoof commented on SolastaCommunityExpansion/Subclasses/Wizard/SpellMaster.cs
> +                BonusRecovery
Settings won’t render until Main.Enabled equals true which happens at the very end of our init code.

2022-03-16 05:21 UTC, ChrisPJohn requested changes

2022-03-16 05:21 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Builders/ConditionDefinitionBuilder.cs
> +            Definition.SetConditionStartParticleReference(new AssetReference());
Should these asset references be set in the initialise?

2022-03-16 05:21 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerBuilder.cs
> +                // This is just an activation time that should not be shown in the UI.
The activation time and costPerUse defaults here were only supposed to be for the power pool related builders that were previously setting them. I don't think they make sense in the base power builder.

2022-03-16 05:21 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerPoolModifierBuilder.cs
> +            // TODO: more validation?
We should probably validate that costPerUse is 1 for the modifier.

2022-03-16 05:21 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerSharedPoolBuilder.cs
> +            // Recharge rate probably shouldn't be in here, but for now leave it be because there is already usage outside of this mod.
Why is this comment here now?

2022-03-16 05:21 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerSharedPoolBuilder.cs
> +            base.Validate();
This should validate that cost per use is 1 and uses determination is fixed.

2022-03-18 15:27 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerSharedPoolBuilder.cs
> +            base.Validate();
done

2022-03-18 15:27 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerSharedPoolBuilder.cs
> +            // Recharge rate probably shouldn't be in here, but for now leave it be because there is already usage outside of this mod.
cut and paste error

2022-03-18 15:27 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerPoolModifierBuilder.cs
> +            // TODO: more validation?
done

2022-03-18 15:27 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerBuilder.cs
> +                // This is just an activation time that should not be shown in the UI.
moved back

2022-03-18 15:28 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/ConditionDefinitionBuilder.cs
> +            Definition.SetConditionStartParticleReference(new AssetReference());
Yes, they were already being done in ctors.  Added same to Initialise.

2022-03-19 01:13 UTC, ChrisPJohn requested changes

2022-03-19 01:13 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionPowerSharedPoolBuilder.cs
> +            base.Validate();
So checking the old code outside of the git diff (because that's a nightmare). I was wrong about cost per use needing to be 1. However we really should validate that usesDetermination is set to fixed. I know it's in the initialize, but since the full power builder is available here it's quite possible a user could change that.

2022-03-19 11:08 UTC, PhilPJL commented
Closed to avoid further conflict.

2022-03-25 19:51 UTC, PhilPJL commented
I'll address issue raised previously

2022-03-27 10:21 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/ConditionDefinitionBuilder.cs
> +            // NOTE: if a constructor is used Initialise won't get called from the DefinitionBuilder base
That was my original plan.  I've added a flag to disable the use of standard Create methods so the builder can force the use of more specialized Create method or constructor.

2022-03-27 10:22 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/ConditionDefinitionBuilder.cs
> +            if (Definition.GetField<AssetReference>("conditionStartParticleReference") == null)
Added ClearParticleReferences and SetEmptyParticleReferencesWhereNull as extension methods.
Used SetEmptyParticleReferencesWhereNull in builder since we may copy an existing definition.

2022-03-27 10:27 UTC, PhilPJL commented
@ChrisPJohn 

added

```
        internal override void Validate()
        {
            base.Validate();

            Preconditions.IsNotNull(Definition.SharedPool, $"FeatureDefinitionPowerSharedPoolBuilder[{Definition.Name}].SharedPool is null.");
            **Preconditions.AreEqual(Definition.UsesDetermination, RuleDefinitions.UsesDetermination.Fixed, $"FeatureDefinitionPowerSharedPoolBuilder[{Definition.Name}].UsesDetermination must be set to Fixed.");**
        }
```

Does your comment above about CostPerUse mean I should remove 

`            Preconditions.AreEqual(Definition.CostPerUse, 1, $"{GetType().Name}[{Definition.Name}].CostPerUse must be set to 1.");
`

from `FeatureDefinitionPowerPoolModifierBuilder `and/or `FeatureDefinitionPowerPoolBuilder`?

2022-03-28 05:23 UTC, ChrisPJohn commented
> 

FeatureDefinitionPowerPoolModifierBuilder and FeatureDefinitionPowerPoolBuilder should both still verify cost per use is 1.

FeatureDefinitionPowerSharedPoolBuilder does not need to validate costPerUse (can be any).

2022-03-28 05:28 UTC, ChrisPJohn approved these changes

2022-03-28 06:47 UTC, merged