add fighting surge feat
ChrisPJohn/SolastaCommunityExpansion pull request #939
Opened 2022-03-15 04:57 UTC by ThyWoof

2022-03-15 07:56 UTC, ChrisPJohn requested changes

2022-03-15 07:56 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Feats/OtherFeats.cs
> +                    AttributeModifierCreed_Of_Misaye,
This does not give strength of dex. You need to make two feats, one for strength one, for dex.

2022-03-15 14:16 UTC, ThyWoof commented on SolastaCommunityExpansion/Feats/OtherFeats.cs
> +                    AttributeModifierCreed_Of_Misaye,
Good call. Will fix later today

2022-03-15 16:56 UTC, PhilPJL reviewed
Looks good to me, but I'll defer to Chris on this.

2022-03-16 04:47 UTC, ChrisPJohn requested changes

2022-03-16 04:47 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Feats/OtherFeats.cs
> +            var pointPoolFeatPracticedExpertSkill = FeatureDefinitionPointPoolBuilder
I didn't think adding pools like this from a feat worked. Does it activate the above proficiency section after you select the feat or add another step to the level up?

2022-03-16 04:47 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Feats/OtherFeats.cs
> +                        .SetDiceByRank((1,1), (5,2))
I believe the game will throw an error if there are missing entries in the dice by rank table. You'll need a value for every possible rank from earliest this could be on a character through 20.

2022-03-16 04:47 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Feats/OtherFeats.cs
> +                     FeatureDefinitionAdditionalDamageBuilder
It looks like this is relying on default values. I'd suggest setting the die type and the advancement type.

2022-03-17 01:38 UTC, ThyWoof commented on SolastaCommunityExpansion/Builders/Features/FeatureDefinitionAdditionalDamageBuilder.cs
> +        //public TBuilder SetAdvancement(RuleDefinitions.AdditionalDamageAdvancement advancement, params DiceByRank[] diceByRanks)
@PhilPJL : this was causing issues when I tried to refer to SetAdvancement... It looks like I'm the first one to use dice by rank.

2022-03-17 03:54 UTC, ChrisPJohn approved these changes

2022-03-17 03:54 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Viewers/Displays/CreditsDisplay.cs
> +            { "Zappastuff", "multiclass, level 20, respec, encounters, dungeon maker editor & pro, inventory sorting, adventure log, epic points, surprise rules, teleport, mod UI & integration, fight
I don't see a primal defense feat

2022-03-17 04:16 UTC, ThyWoof commented on SolastaCommunityExpansion/Viewers/Displays/CreditsDisplay.cs
> +            { "Zappastuff", "multiclass, level 20, respec, encounters, dungeon maker editor & pro, inventory sorting, adventure log, epic points, surprise rules, teleport, mod UI & integration, fight
I’m working on other feats. Will fix credits on another request.

2022-03-17 04:17 UTC, merged