Zappa Feats
ChrisPJohn/SolastaCommunityExpansion pull request #964
Opened 2022-03-20 21:14 UTC by ThyWoof

changed Feats:

* Metamagic feats now requires Character Level 4 (Heightened required level 8)
* Nerfed Shady feat with a slower sneak damage progression

added new Feats:

* Brutal Thug - sneak attacks with martial weapons and fighter weapon proficiency
* Metamagic: Heightened - learn Heightened and gain 4 sorcery points

added new interface:

* IValidateFeatPrerequisites - allows custom code to add custom validations to Feats. I.e.: enforcing Character Level on metamagic feats)

extended AttributeModifier calculation:

* add new modifier AdditiveAtEnd - allows addition after multiply / multiply by level / multiply by class level (default additive modifier happens before multiplications)

moved 2 patches from GameUI/LevelUp into CustomFeatures.

2022-03-21 00:55 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/159193625-158c6d41-5690-4c0f-a8e1-0d3e77303800.png)
different titles for custom fighting styles and them as feats.

2022-03-21 02:58 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/159199675-edc5e56c-51aa-4858-b303-2f2be23c880a.png)
these descriptions in one line are a game bug. I shared with TA and got confirmation on a fix.

2022-03-21 03:05 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/159200112-ea65a37c-7e65-4f63-87d6-95b2c3eb6e01.png)
![image](https://user-images.githubusercontent.com/13087646/159200159-71051ee5-b5d1-427a-bddd-e326e36a76ed.png)

2022-03-21 03:13 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/159200337-8392211c-1020-41b5-8d10-0afc07ed64eb.png)
Sorcerer Level 4 with 1 metamagic feat. Sorcery Points = 4 (level) + 2 (feat).

![image](https://user-images.githubusercontent.com/13087646/159200566-6aeb908a-12ba-4684-be8d-79903378b3d5.png)
Sorcerer Level 8 with 2 metamagic feats. Sorcery Points = 8 (level) + 2 (feat) + 4 (Heightened Feat)

2022-03-21 06:03 UTC, ChrisPJohn requested changes

2022-03-21 06:03 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/CustomFeatures/AtttributeModifierBonus/RulesetAttributePatcher.cs
> +        internal static void Postfix(RulesetAttribute __instance, ref int ___currentValue)
I think we can have a simpler patch. So before attributemodifiers are applied, they are generally sorted. With the sort order being determined by a comparison between the operation enum values (and then several tie break checks). 

Since the value you chose for the enum means it will get sorted to the end of the list, you could add a postfix to RulesetAttributeModifier.ApplyOnValue and just do the addition there.

2022-03-21 23:26 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/CustomFeatures/AtttributeModifierBonus/RulesetAttributePatcher.cs
> +        internal static void Postfix(RulesetAttribute __instance, ref int ___currentValue)
ok.

2022-03-21 23:36 UTC, ThyWoof commented
@ChrisPJohn : applied the requested changes and validated pool calculation was still correct. same on pre reqs. still working after refactor.

2022-03-22 03:15 UTC, ThyWoof commented
The Feat builder can now accept one or more validation delegates for more complex scenarios.

2022-03-22 04:35 UTC, ChrisPJohn requested changes

2022-03-22 04:35 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Feats/FeatsValidations.cs
> +        internal static bool ValidateMinCharacterLevel4(
The reason I suggested an abstract class where you provide the function as part of the class was you could add relevant values to the class as fields. So the you'd be able to have 1 new class for level prereqs, and set the level to check on that class.

2022-03-22 04:35 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Feats/FeatsValidations.cs
> +        internal static bool ValidateNotBarbarian(
For all of these feats that require not being a character class what happens with multiclassing?

2022-03-22 04:35 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/CustomFeatures/FeatsPrerequisites/GuiFeatDefinitionPatcher.cs
> +            foreach (IsFeatMacthingPrerequisites isFeatMacthingPrerequisites in featDefinitionWithPrereqs.IsFeatMacthingPrerequisites.GetInvocationList())
I don't believe this needs to be a list. It's a function that can be defined by the modder. If they want to check multiple things in the one function they can.

2022-03-22 04:57 UTC, ThyWoof commented on SolastaCommunityExpansion/Feats/FeatsValidations.cs
> +        internal static bool ValidateNotBarbarian(
won't cover MC use case here. if someone takes a class after the feat that's fine.

2022-03-22 04:59 UTC, ThyWoof commented on SolastaCommunityExpansion/Feats/FeatsValidations.cs
> +        internal static bool ValidateMinCharacterLevel4(
I followed the pattern I found on FeatureDefinitionConditionAffinityBuilder. It's easier when I have some code I can read as my C# knowledge isn't that sharp.

2022-03-22 05:00 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/CustomFeatures/FeatsPrerequisites/GuiFeatDefinitionPatcher.cs
> +            foreach (IsFeatMacthingPrerequisites isFeatMacthingPrerequisites in featDefinitionWithPrereqs.IsFeatMacthingPrerequisites.GetInvocationList())
There will a lot of repetition code in validations otherwise. I tested this scenario and it works fine. Tried to be modular here.

2022-03-22 05:01 UTC, ThyWoof commented on SolastaCommunityExpansion/Feats/FeatsValidations.cs
> +        internal static bool ValidateMinCharacterLevel4(
If you could point me out to some full examples...

2022-03-22 17:13 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/159537255-d5dd50f0-0b3e-4796-a480-1a042c6fdac9.png)
@ChrisPJohn : here is an example where having modular validation routines make sense. I want Brutal Thug to only be allowed after level 4 but only if hero has sneak attacks. Added 2 validations to this feat.

2022-03-22 17:14 UTC, ThyWoof commented
I also renamed to FeatDefinitionCustom so if we ever need more custom behavior we keep extending this class and corresponding builder.

2022-03-22 17:46 UTC, PhilPJL commented on SolastaCommunityExpansion/Feats/FeatsValidations.cs
> +        internal static IsFeatMacthingPrerequisites ValidateMinCharLevel(int minCharLevel)
Spelling 'IsFeatMatching'

2022-03-22 17:49 UTC, PhilPJL commented
Validation may fit in with what was proposed on #938 which I closed.  May be worth re-opening.

2022-03-22 19:54 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/FeatDefinitionCustomBuilder.cs
> +    public class FeatDefinitionCustom : FeatDefinition
Is this the right name?  'Custom' is a bit generic, what is this feat definition's purpose?  Should it be FeatDefinitionWithValidation (something like that?)

2022-03-22 20:25 UTC, PhilPJL commented on SolastaCommunityExpansion/Feats/FeatsValidations.cs
> +        internal static IsFeatMatchingPrerequisites ValidateMinCharLevel(int minCharLevel)
I like it but I wouldn't have used (or thought of tbh) delegates, I would have used Func<def, hero, (bool, string)>.  
The string concatenation doesn't belong in the validators they should return the result (bool, string) only.  There should then be a helper method somewhere to concat the strings.  `string.Join("\n", results)`

2022-03-22 20:26 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/FeatDefinitionCustomBuilder.cs
> +        public IsFeatMatchingPrerequisites IsFeatMatchingPrerequisites;
make it a property.  Not good practice to have public fields.

2022-03-22 20:26 UTC, PhilPJL commented on SolastaCommunityExpansion/Builders/FeatDefinitionCustomBuilder.cs
> +        public IsFeatMatchingPrerequisites IsFeatMatchingPrerequisites;
or is it for delegates?

2022-03-22 20:34 UTC, PhilPJL commented on SolastaCommunityExpansion/Patches/CustomFeatures/FeatsPrerequisites/GuiFeatDefinitionPatcher.cs
> +            if (feat is not FeatDefinitionCustom FeatDefinitionCustom || FeatDefinitionCustom.IsFeatMatchingPrerequisites == null)
lower case please `featDefinitionCustom `

2022-03-22 20:40 UTC, PhilPJL commented on SolastaCommunityExpansion/Patches/CustomFeatures/FeatsPrerequisites/GuiFeatDefinitionPatcher.cs
> +            foreach (IsFeatMatchingPrerequisites IsFeatMatchingPrerequisites in FeatDefinitionCustom.IsFeatMatchingPrerequisites.GetInvocationList())
I guess I would put this logic in FeatDefinitionCustom 

```
void Test(ref bool __result, ref string prerequisiteOutput)
{
	var feat = new FeatDefinitionCustom();

// and call it here
	var (result, output) = feat.Validate();
	
	__result = result;
	prerequisiteOutput = output;
}

class FeatDefinitionCustom
{
	public (bool result, string output) Validate()
	{
		// call all validators 
		// concat output appropriately
		// return result appropriately
		
		return (true, "It's all good");
	}
}
```

2022-03-22 21:39 UTC, ThyWoof commented
> I also renamed to FeatDefinitionCustom so if we ever need more custom behavior we keep extending this class and corresponding builder.

It was named FeatDefinitionWithPrereqs before. I can revert that.

2022-03-22 21:40 UTC, ThyWoof commented on SolastaCommunityExpansion/Builders/FeatDefinitionCustomBuilder.cs
> +        public IsFeatMatchingPrerequisites IsFeatMatchingPrerequisites;
it's a delegate. gotta be public.

2022-03-22 21:40 UTC, ThyWoof commented on SolastaCommunityExpansion/Feats/FeatsValidations.cs
> +        internal static IsFeatMatchingPrerequisites ValidateMinCharLevel(int minCharLevel)
using delegates to have modular validations. I'm also following the same pattern on game code that call these checks in sequence, updating the ref everytime.

2022-03-22 21:41 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/CustomFeatures/FeatsPrerequisites/GuiFeatDefinitionPatcher.cs
> +            if (feat is not FeatDefinitionCustom FeatDefinitionCustom || FeatDefinitionCustom.IsFeatMatchingPrerequisites == null)
ok

2022-03-22 21:42 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/CustomFeatures/FeatsPrerequisites/GuiFeatDefinitionPatcher.cs
> +            foreach (IsFeatMatchingPrerequisites IsFeatMatchingPrerequisites in FeatDefinitionCustom.IsFeatMatchingPrerequisites.GetInvocationList())
check GuiFeatDefinition.IsFeatMacthingPrerequisites to understand why I chose this pattern.

2022-03-22 21:43 UTC, ThyWoof commented on SolastaCommunityExpansion/Builders/FeatDefinitionCustomBuilder.cs
> +    public class FeatDefinitionCustom : FeatDefinition
It was named FeatDefinitionWithPrereqs before. I can revert that.

2022-03-22 21:44 UTC, ThyWoof commented on SolastaCommunityExpansion/Feats/FeatsValidations.cs
> +        internal static IsFeatMatchingPrerequisites ValidateMinCharLevel(int minCharLevel)
I disagree with string not belonging on validations. The way I wrote make validation routines self contained. You can mix and match more than one on same Feat.

2022-03-22 23:21 UTC, ThyWoof commented
@PhilPJL / @ChrisPJohn : applied suggestions by Imp. Code is cleaner now on validation routines and it seems to be faster as it joins all results together.

2022-03-22 23:40 UTC, ThyWoof commented
![Uploading image.png…]()

2022-03-22 23:41 UTC, ThyWoof commented
![image](https://user-images.githubusercontent.com/13087646/159593884-bcf9dee8-8a94-4287-bb70-cd09cc868d41.png)
@ChrisPJohn : I ended up setting WarCaster to require spell casting. There was a bug on the code removing this validation that got fixed.

2022-03-23 04:08 UTC, ChrisPJohn requested changes

2022-03-23 04:08 UTC, ChrisPJohn commented on SolastaCommunityExpansion/Patches/CustomFeatures/FeatDefinitionCustomCode/GuiFeatDefinitionPatcher.cs
> +                ? 1
If we just wanted to have this always on, the patch could be a lot simpler. Why are you making this change?

2022-03-23 05:04 UTC, closed without merging